import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {defaultState,cardPaymentForecast,summarize} from '../assets/js/domain.js';
import {BudgetRepository} from '../assets/js/repository.js';
import {FIRST_MONTH,validMonth,validateCycleExtras,cardUsagePeriod,cashUsagePeriod,changedCard,changedCashHistory,cycleSummary,categoryOrder,quickInstallment,editedInstallment,entryTime} from '../assets/js/cycles.js';
import {cycleHeroHtml,cycleDetailHtml} from '../assets/js/cycle-ui.js';
const card=(id='a',patch={})=>({id,name:`테스트 카드 ${id}`,issuer:'테스트',active:true,billingDay:20,cycleRule:{type:'previous-current',startDay:11,endDay:10},...patch});
let sequence=0;
const tx=(patch={})=>({id:`test-${++sequence}`,date:'2026-09-03',time:'12:34',amount:10000,type:'expense',merchant:'합성 테스트 상점',categoryId:'food',paymentMethod:'card',cardId:'a',source:'manual',sourceId:'',memo:'',installment:null,cancelled:false,...patch});
function fixture(){const s=defaultState();s.cards=[card()];s.settings.cashCycleHistory=[{fromMonth:FIRST_MONTH,rule:{type:'previous-current',startDay:11,endDay:10}}];return s;}
class MemoryStorage{
 constructor(data=defaultState()){this.value=structuredClone(data);this.saves=0;this.backups=[];this.fail=false;}
 async load(){return structuredClone(this.value);}
 async save(next,expected,{backup=false}={}){if(this.fail)throw new Error('quota');if(this.value.revision!==expected)throw new Error('revision conflict');if(backup)this.backups.push(structuredClone(this.value));this.value=structuredClone(next);this.saves++;}
 async reset(next,expected){await this.save(next,expected);}
}
async function repository(initial=fixture()){const storage=new MemoryStorage(initial),repo=new BudgetRepository(storage);await repo.init();return{repo,storage};}
test('billing month selects previous-current window inclusive, not the containing date',()=>{
 const s=fixture();s.transactions=[tx({date:'2026-08-10'}),tx({date:'2026-08-11',amount:11000}),tx({date:'2026-09-10',amount:22000}),tx({date:'2026-09-11',amount:44000})];const sum=cycleSummary(s,'2026-09');
 assert.equal(sum.total,33000);assert.equal(sum.samePeriod.start,'2026-08-11');assert.equal(sum.samePeriod.end,'2026-09-10');assert.equal(cycleSummary(s,'2026-10').total,44000);
});
test('usage remains after due date while the unchanged forecast may be zero',()=>{const s=fixture();s.transactions=[tx()];assert.equal(cardPaymentForecast(s.transactions,s.cards,'2026-09-22').current[0].total,0);assert.equal(cycleSummary(s,'2026-09').total,10000);});
test('cash, account and card fixed expenses are disjoint and totals reconcile to entries',()=>{
 const s=fixture();s.transactions=[tx(),tx({categoryId:'subscription',recurringExpenseId:'x',amount:2000}),tx({paymentMethod:'cash',cardId:null,amount:3000,categoryId:'housing'}),tx({paymentMethod:'account',cardId:null,amount:4000}),tx({type:'transfer',amount:99000}),tx({type:'income',amount:88000}),tx({projected:true,amount:77000})];const sum=cycleSummary(s,'2026-09');
 assert.equal(sum.cardTotal,12000);assert.equal(sum.cashFixed,3000);assert.equal(sum.cashExpense,4000);assert.equal(sum.total,19000);assert.equal(sum.total,sum.entries.reduce((n,e)=>n+e.amount,0));
});
test('refund-only period stays negative rather than being clamped to zero',()=>{const s=fixture();s.transactions=[tx({cancelled:true,amount:15000}),tx({paymentMethod:'cash',cardId:null,cancelled:true,amount:500})];const sum=cycleSummary(s,'2026-09');assert.equal(sum.cardTotal,-15000);assert.equal(sum.cashTotal,-500);assert.equal(sum.total,-15500);});
test('legacy installment amounts remain unchanged even when installment input is off',()=>{const s=fixture();s.settings.installmentsEnabled=false;s.transactions=[tx({date:'2026-08-03',amount:10001,installment:{months:3}})];const before=structuredClone(s);const row=cycleSummary(s,'2026-09').entries[0];assert.equal(row.amount,3334);assert.equal(row.installmentIndex,2);assert.deepEqual(s,before);});
test('inactive and identically named cards remain separate by id',()=>{const s=fixture();s.cards=[card('a',{name:'같은 이름'}),card('b',{active:false,name:'같은 이름'}),card('c',{active:false})];s.transactions=[tx(),tx({cardId:'b',amount:6000})];const sum=cycleSummary(s,'2026-09');assert.equal(sum.cardRows.length,2);assert.deepEqual(sum.cardRows.map(r=>r.total),[10000,6000]);});
test('each card uses its own billing window and unknown cards are not silently guessed',()=>{const s=fixture();s.cards.push(card('b',{cycleRule:{type:'previous-current',startDay:16,endDay:15}}));s.transactions=[tx({date:'2026-09-12'}),tx({cardId:'b',date:'2026-09-12',amount:7000}),tx({cardId:null,paymentMethod:'card',amount:8000})];const sum=cycleSummary(s,'2026-09');assert.equal(sum.total,7000);assert.equal(sum.samePeriod,null);assert.equal(sum.unresolved.length,1);});
test('invalid card period is reported without deleting the ledger',()=>{const s=fixture();s.cards[0].cycleRule={type:'unknown'};s.transactions=[tx()];const before=structuredClone(s),sum=cycleSummary(s,'2026-09');assert.equal(sum.unresolved.length,1);assert.equal(sum.cardTotal,0);assert.ok(sum.warnings.length);assert.deepEqual(s,before);});
test('month validation rejects impossible and prototype keys',()=>{for(const m of ['2026-00','2026-13','__proto__','2026-9','foo'])assert.equal(validMonth(m),false);assert.throws(()=>cycleSummary(fixture(),'2026-13'));});
test('cash default is transparent calendar month until explicitly configured',()=>{assert.deepEqual(cashUsagePeriod({},'2026-09'),{start:'2026-09-01',end:'2026-09-30',ruleType:'calendar-month'});});
test('cash month ends and year boundary use calendar arithmetic',()=>{const settings={cashCycleHistory:[{fromMonth:FIRST_MONTH,rule:{type:'previous-current',startDay:31,endDay:30}}]};assert.equal(cashUsagePeriod(settings,'2028-03').start,'2028-02-29');assert.equal(cashUsagePeriod(settings,'2027-03').start,'2027-02-28');assert.equal(cardUsagePeriod(card(),'2027-01').start,'2026-12-11');});
test('card period edit affects chosen month onwards and preserves earlier summary',()=>{const old=card(),changed=changedCard(old,{...old,cycleRule:{type:'previous-current',startDay:16,endDay:15}},'2026-09','2026-09');assert.equal(cardUsagePeriod(changed,'2026-08').start,'2026-07-11');assert.equal(cardUsagePeriod(changed,'2026-09').start,'2026-08-16');assert.equal(changed.cycleHistory.length,2);assert.equal(old.cycleHistory,undefined);});
test('cash period history preserves older periods and keeps month selection explicit',()=>{const settings={cashCycleHistory:changedCashHistory({}, {type:'previous-current',startDay:11,endDay:10},'2026-09')};assert.equal(cashUsagePeriod(settings,'2026-08').start,'2026-08-01');assert.equal(cashUsagePeriod(settings,'2026-09').start,'2026-08-11');});
test('period gaps or overlaps are surfaced, not silently hidden',()=>{const s=fixture();s.cards[0].cycleRule={type:'previous-current',startDay:11,endDay:15};assert.ok(cycleSummary(s,'2026-09').warnings.some(w=>w.includes('겹침')));});
test('new optional fields leave old data intact without a startup save',async()=>{const s=fixture();delete s.settings.cashCycleHistory;s.transactions=[tx({installment:{months:3}})];const {repo,storage}=await repository(s);assert.deepEqual(repo.state,s);assert.equal(storage.saves,0);assert.equal(repo.state.settings.installmentsEnabled,undefined);});
test('monthly memo persists independently and never creates spending',async()=>{const {repo,storage}=await repository();await repo.setCycleNote('2026-09','합성 메모: 10만원 이체','');await repo.setCycleNote('2026-10','다음 달 메모','');const reloaded=new BudgetRepository(storage);await reloaded.init();assert.equal(cycleSummary(reloaded.state,'2026-09').note,'합성 메모: 10만원 이체');assert.equal(cycleSummary(reloaded.state,'2026-09').total,0);assert.equal(cycleSummary(reloaded.state,'2026-10').note,'다음 달 메모');});
test('stale memo save is rejected without changing data',async()=>{const {repo}=await repository();await repo.setCycleNote('2026-09','first','');const before=structuredClone(repo.state);await assert.rejects(repo.setCycleNote('2026-09','stale',''),/변경/);assert.deepEqual(repo.state,before);});
test('failed note, period and flag writes preserve memory and storage',async()=>{const {repo,storage}=await repository(),before=structuredClone(repo.state);storage.fail=true;await assert.rejects(repo.setCycleNote('2026-09','failed',''),/quota/);await assert.rejects(repo.setCashCycle({type:'calendar-month'},'2026-09'),/quota/);await assert.rejects(repo.setting({installmentsEnabled:true}),/quota/);assert.deepEqual(repo.state,before);assert.deepEqual(storage.value,before);});
test('foreign revision prevents late writes from a stale repository',async()=>{const {repo,storage}=await repository(),other=new BudgetRepository(storage);await other.init();await repo.setCycleNote('2026-09','first','');await assert.rejects(other.setCycleNote('2026-09','late',''),/revision conflict/);assert.equal(storage.value.meta.cycleNotes['2026-09'].text,'first');});
test('whole JSON backup round-trip preserves all settings, notes and old installments',async()=>{const {repo}=await repository();await repo.setCycleNote('2026-09','백업 검증','');await repo.setting({installmentsEnabled:true});await repo.addTransaction(tx({installment:{months:3}}));const backup=JSON.parse(JSON.stringify(repo.state)),target=await repository();await target.repo.restoreFullBackup(backup);assert.equal(target.repo.state.revision,1);assert.deepEqual(target.repo.state.transactions,backup.transactions);assert.deepEqual(target.repo.state.meta.cycleNotes,backup.meta.cycleNotes);assert.deepEqual(target.repo.state.settings,backup.settings);assert.equal(target.storage.backups.length,1);});
test('restore failure and malformed extension keep current state and old backup safe',async()=>{const {repo,storage}=await repository();const before=structuredClone(repo.state),bad=structuredClone(before);bad.meta.cycleNotes={'2026-13':{text:'bad',updatedAt:''}};await assert.rejects(repo.restoreFullBackup(bad));storage.fail=true;await assert.rejects(repo.restoreFullBackup(before),/quota/);assert.deepEqual(repo.state,before);assert.deepEqual(storage.value,before);});
test('old backup without new fields remains readable and restores with local revision',async()=>{const {repo}=await repository();await repo.setCycleNote('2026-09','existing','');const old=defaultState();old.revision=9900;await repo.restoreFullBackup(old);assert.equal(repo.state.revision,2);assert.equal(repo.state.settings.installmentsEnabled,undefined);assert.equal(repo.state.meta.cycleNotes,undefined);});
test('category order uses frequency rather than amount and ignores cancellation, income and future rows',()=>{const s=fixture();s.transactions=[tx({categoryId:'food',amount:9999999}),tx({categoryId:'cafe',amount:1}),tx({categoryId:'cafe',amount:2}),...Array.from({length:5},()=>tx({categoryId:'housing',cancelled:true})),tx({categoryId:'living',type:'transfer'}),tx({categoryId:'living',type:'income'}),tx({categoryId:'housing',date:'2027-01-01'}),tx({categoryId:'housing',projected:true})];const before=structuredClone(s.categories);assert.deepEqual(categoryOrder(s,'expense','2026-09-22').slice(0,2).map(c=>c.id),['cafe','food']);assert.deepEqual(s.categories,before);});
test('category tie uses last use then the original stable order',()=>{const s=fixture();assert.deepEqual(categoryOrder(s).map(c=>c.id),s.categories.map(c=>c.id));s.transactions=[tx({categoryId:'food',date:'2026-09-01'}),tx({categoryId:'cafe',date:'2026-09-02'})];assert.equal(categoryOrder(s,'expense','2026-09-22')[0].id,'cafe');});
test('quick installment requires explicit enabled setting and card expense',()=>{assert.equal(quickInstallment({},'expense','card:a',3),null);assert.deepEqual(quickInstallment({installmentsEnabled:true},'expense','card:a',3),{months:3});for(const payment of ['cash','account'])assert.equal(quickInstallment({installmentsEnabled:true},'expense',payment,3),null);assert.equal(quickInstallment({installmentsEnabled:true},'transfer','card:a',3),null);assert.throws(()=>quickInstallment({installmentsEnabled:true},'expense','card:a',37));});
test('editing an old installment with the feature off preserves its metadata',()=>{const old=tx({installment:{months:3,legacy:'keep'}});assert.deepEqual(editedInstallment({},old,'expense','card:a',null),old.installment);assert.throws(()=>editedInstallment({},old,'expense','cash',null));assert.equal(editedInstallment({},tx(),'expense','card:a',null),null);});
test('no time input is required; metadata time is h23 in the configured time zone',()=>{const date=new Date('2026-09-21T15:01:00Z');assert.equal(entryTime('Asia/Seoul',date),'00:01');assert.equal(entryTime('America/New_York',date),'11:01');});
test('summary rendering escapes notes, card names and merchants',()=>{const s=fixture();s.cards[0].name='<img src=x onerror=alert(1)>';s.meta.cycleNotes={'2026-09':{text:'<script>bad()</script>',updatedAt:''}};s.transactions=[tx({merchant:'<script>bad()</script>'})];for(const html of [cycleHeroHtml(s,'2026-09'),cycleDetailHtml(s,'2026-09'),cycleDetailHtml(s,'2026-09','all')]){assert.equal(html.includes('<script>'),false);assert.equal(html.includes('<img '),false);}});
test('quick UI has no time field and uses ordered categories, guarded installment and full restore',async()=>{const source=await readFile(new URL('../assets/js/app.js',import.meta.url),'utf8'),quick=source.slice(source.indexOf('function addView()'),source.indexOf('function barRows'));assert.equal(quick.includes('name="time"'),false);assert.ok(quick.includes('categoryOrder'));assert.ok(quick.includes('installmentsEnabled===true'));assert.ok(source.includes('entryTime(state().settings.timeZone)'));assert.ok(source.includes('showFullBackupRestore'));});
test('monthly statistics and budgets are not converted to cycle statistics',()=>{const s=fixture();s.transactions=[tx({date:'2026-08-20',amount:2000}),tx({date:'2026-09-15',amount:3000})];assert.equal(cycleSummary(s,'2026-09').total,2000);assert.equal(summarize(s.transactions,{month:'2026-09'}).expense,3000);});
test('precache contains every runtime module URL including unchanged dependencies',async()=>{
 const {default:vm}=await import('node:vm'),sw=await readFile(new URL('../sw.js',import.meta.url),'utf8'),context={self:{addEventListener(){}}};vm.runInNewContext(sw+';this.assets=ASSETS;',context);
 const assets=new Set(context.assets),seen=new Set();
 async function check(path){if(seen.has(path))return;seen.add(path);assert.ok(assets.has('./'+path),`missing precache ${path}`);const code=await readFile(new URL('../'+path.split('?')[0],import.meta.url),'utf8');for(const m of code.matchAll(/from\s*['"]\.\/([^'"]+)['"]/g))await check('assets/js/'+m[1]);}
 await check('assets/js/app.js?v=1.7.2');assert.ok(assets.has('./assets/css/cycle.css?v=1.7.1'));
});
test('service-worker activation preserves other apps and the budget share inbox',async()=>{
 const {default:vm}=await import('node:vm'),handlers={},deleted=[],context={self:{addEventListener:(name,fn)=>handlers[name]=fn,clients:{claim:async()=>{}}},caches:{keys:async()=>['budget-pwa-v14-cycle-summary','budget-pwa-v15-zero-expense','budget-share-inbox-v1','bookshelf-reading-test','workout-log-test','haru-page-test'],delete:async key=>deleted.push(key)}};
 vm.runInNewContext(await readFile(new URL('../sw.js',import.meta.url),'utf8'),context);let pending;handlers.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(deleted,['budget-pwa-v14-cycle-summary','budget-pwa-v15-zero-expense']);
});
test('editing an earlier card period is not lost just because it matches the current rule',()=>{const old=card(),newValue={...old,cycleRule:{type:'previous-current',startDay:16,endDay:15}};const first=changedCard(old,newValue,'2026-09','2026-09'),earlier=changedCard(first,newValue,'2026-08','2026-09');assert.equal(cardUsagePeriod(earlier,'2026-08').start,'2026-07-16');assert.equal(cardUsagePeriod(earlier,'2026-07').start,'2026-06-11');});
test('cash gaps are reported and unsupported cash rules cannot be silently reinterpreted',()=>{const s=fixture();s.settings.cashCycleHistory[0].rule.endDay=15;assert.ok(cycleSummary(s,'2026-09').warnings.some(w=>w.startsWith('현금·계좌')));assert.throws(()=>changedCashHistory({}, {type:'monthly-range',startDay:11,endDay:10,dueMonthOffset:1},'2026-09'));});
