import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';
const read=path=>readFile(new URL(path,import.meta.url),'utf8');
test('service worker has budget-only cache, version asset and request boundary',async()=>{const sw=await read('../sw.js');assert.match(sw,/budget-pwa-v3-reset-expense-only/);assert.match(sw,/notion-export\.js/);assert.match(sw,/version\.json/);assert.match(sw,/\/budget\//);assert.doesNotMatch(sw,/reading-|workout-/);});
test('manifest scope is isolated and share target avoids sensitive GET query strings',async()=>{const manifest=JSON.parse(await read('../manifest.webmanifest'));assert.equal(manifest.scope,'./');assert.equal(manifest.start_url,'./');assert.equal(manifest.share_target.method,'POST');assert.equal(manifest.share_target.enctype,'multipart/form-data');});
test('mobile stylesheet keeps a one-column form at 420px',async()=>{const css=await read('../assets/css/app.css');assert.match(css,/@media\(max-width:420px\)/);assert.match(css,/\.form-grid\{grid-template-columns:1fr\}/);assert.match(css,/overflow-x:hidden/);});
test('WebMCP exposes a read tool and the same transaction creation path',async()=>{const app=await read('../assets/js/app.js');assert.match(app,/name:'read_budget_summary'/);assert.match(app,/name:'create_budget_transaction'/);assert.match(app,/await repo\.addTransaction/);});
test('settings expose version, refresh and guarded budget reset controls',async()=>{const app=await read('../assets/js/app.js');assert.match(app,/APP_VERSION='1\.2\.0'/);assert.match(app,/id="check-version"/);assert.match(app,/id="refresh-app"/);assert.match(app,/id="reset-budget"/);assert.match(app,/마지막 기회입니다\. 그래도 하시겠습니까/);assert.match(app,/await repo\.resetAll\(\)/);});
test('deployed version metadata matches the app version',async()=>{const version=JSON.parse(await read('../version.json')),app=await read('../assets/js/app.js');assert.equal(version.version,'1.2.0');assert.match(app,new RegExp(`APP_VERSION='${version.version.replaceAll('.','\\.')}'`));});
test('visible app controls and WebMCP no longer offer income entry or statistics',async()=>{const app=await read('../assets/js/app.js');assert.doesNotMatch(app,/\['income','수입'\]/);assert.doesNotMatch(app,/월별 수입|연도별 수입|이번 달 수입/);assert.match(app,/enum:\['expense','transfer'\]/);});
