import test from'node:test';import assert from'node:assert/strict';import{BudgetRepository}from'../assets/js/repository.js';import{cardPaymentForecast,projectedCardTransactions,defaultState}from'../assets/js/domain.js';
class MemoryStorage{constructor(value=null){this.value=value;this.saves=0;}async load(){return structuredClone(this.value);}async save(next,revision){if((this.value?.revision??0)!==revision)throw new Error('conflict');this.value=structuredClone(next);this.saves++;}async reset(next,revision){if((this.value?.revision??0)!==revision)throw new Error('conflict');this.value=structuredClone(next);this.saves++;}}
const item={date:'2026-09-11',time:'12:00',type:'expense',amount:1200,merchant:'편의점',categoryId:'living',paymentMethod:'cash',cardId:null,source:'manual',sourceId:'',memo:'',installment:null,cancelled:false,linkedOriginal:null};
test('CRUD writes one authoritative revision at a time',async()=>{const store=new MemoryStorage(),repo=new BudgetRepository(store);await repo.init();const added=await repo.addTransaction(item);assert.equal(repo.state.revision,1);await repo.updateTransaction(added.id,{memo:'수정'});assert.equal(repo.state.transactions[0].memo,'수정');await repo.removeTransaction(added.id);assert.equal(repo.state.transactions.length,0);assert.equal(repo.state.revision,3);});
test('automatic duplicate registration is blocked',async()=>{const repo=new BudgetRepository(new MemoryStorage());await repo.init();await repo.addTransaction(item);await assert.rejects(()=>repo.addTransaction(item),/같은 거래/);assert.equal(repo.state.transactions.length,1);});
test('invalid persisted state is never automatically reset',async()=>{const store=new MemoryStorage({revision:8,transactions:[]}),repo=new BudgetRepository(store);await assert.rejects(()=>repo.init(),/항목이 없어요/);assert.equal(store.saves,0);assert.equal(store.value.revision,8);});
test('theme persistence and atomic import share normal commit path',async()=>{const repo=new BudgetRepository(new MemoryStorage(defaultState()));await repo.init();await repo.setting({theme:'green'});assert.equal(repo.state.settings.theme,'green');await repo.applyImport({transactions:[{id:'imported',...item,createdAt:'2026-09-11T00:00:00Z',updatedAt:'2026-09-11T00:00:00Z'}],importRecord:{id:'imp',kind:'test'},metaPatch:{lastNotionSync:'now'}});assert.equal(repo.state.transactions.length,1);assert.equal(repo.state.meta.lastNotionSync,'now');});
test('Notion export categories and transactions are committed atomically',async()=>{const store=new MemoryStorage(defaultState()),repo=new BudgetRepository(store);await repo.init();await repo.applyImport({categories:[{id:'notion_gift',name:'선물',kind:'expense',fixed:false}],transactions:[{id:'gift',...item,categoryId:'notion_gift',source:'notion',billingDate:'2026-10-10',createdAt:'2026-09-11T00:00:00Z',updatedAt:'2026-09-11T00:00:00Z'}]});assert.equal(repo.state.categories.at(-1).name,'선물');assert.equal(repo.state.transactions[0].billingDate,'2026-10-10');assert.equal(store.saves,1);});
test('failed import leaves both previous categories and transactions unchanged',async()=>{const store=new MemoryStorage(defaultState()),repo=new BudgetRepository(store);await repo.init();store.save=async()=>{throw new Error('disk full');};const before=structuredClone(repo.state);await assert.rejects(()=>repo.applyImport({categories:[{id:'new',name:'새 분류',kind:'expense',fixed:false}],transactions:[{id:'bad',...item,date:'broken'}]}));assert.deepEqual(repo.state,before);});
test('explicit reset replaces all budget data and advances the revision fence',async()=>{const initial=defaultState();initial.revision=7;initial.transactions=[{id:'old',...item,createdAt:'2026-09-11T00:00:00Z',updatedAt:'2026-09-11T00:00:00Z'}];initial.cards=[{id:'card'}];const store=new MemoryStorage(initial),repo=new BudgetRepository(store);await repo.init();await repo.resetAll();assert.equal(repo.state.revision,8);assert.equal(repo.state.transactions.length,0);assert.equal(repo.state.cards.length,0);assert.equal(repo.state.budgets.length,0);assert.equal(repo.state.imports.length,0);assert.equal(repo.state.categories.some(category=>category.kind==='income'),false);});
test('failed reset never changes the in-memory or persisted budget',async()=>{const initial=defaultState(),store=new MemoryStorage(initial),repo=new BudgetRepository(store);await repo.init();const before=structuredClone(repo.state);store.reset=async()=>{throw new Error('blocked');};await assert.rejects(()=>repo.resetAll(),/blocked/);assert.deepEqual(repo.state,before);assert.deepEqual(store.value,before);});
test('new income transactions and imports are rejected while legacy snapshots still load',async()=>{const legacy=defaultState();legacy.transactions=[{id:'legacy-income',...item,type:'income',createdAt:'2026-09-11T00:00:00Z',updatedAt:'2026-09-11T00:00:00Z'}];const repo=new BudgetRepository(new MemoryStorage(legacy));await repo.init();assert.equal(repo.state.transactions.length,1);await assert.rejects(()=>repo.addTransaction({...item,type:'income'}),/지원하지 않는/);await assert.rejects(()=>repo.applyImport({transactions:[legacy.transactions[0]]}),/지원하지 않는/);});
test('recurring expense is generated once per due month and catches up later months',async()=>{const repo=new BudgetRepository(new MemoryStorage());await repo.init();await repo.upsertRecurringExpense({name:'월세',amount:500000,day:10,categoryId:'housing',startMonth:'2026-09'},'2026-09-13');assert.equal(repo.state.transactions.length,1);assert.equal(repo.state.transactions[0].date,'2026-09-10');assert.deepEqual(repo.state.recurringExpenses[0].generatedMonths,['2026-09']);await repo.materializeRecurringExpenses('2026-09-30');assert.equal(repo.state.transactions.length,1);await repo.materializeRecurringExpenses('2026-10-10');assert.equal(repo.state.transactions.length,2);assert.equal(repo.state.transactions[0].date,'2026-10-10');});
test('recurring expense waits until its monthly date and removal keeps past transactions',async()=>{const repo=new BudgetRepository(new MemoryStorage());await repo.init();const rule=await repo.upsertRecurringExpense({name:'구독',amount:12000,day:25,categoryId:'subscription',startMonth:'2026-09'},'2026-09-13');assert.equal(repo.state.transactions.length,0);await repo.materializeRecurringExpenses('2026-09-25');assert.equal(repo.state.transactions.length,1);await repo.removeRecurringExpense(rule.id);assert.equal(repo.state.recurringExpenses.length,0);assert.equal(repo.state.transactions.length,1);});
test('failed recurring-expense save changes neither rules nor generated transactions',async()=>{const store=new MemoryStorage(),repo=new BudgetRepository(store);await repo.init();const before=structuredClone(repo.state);store.save=async()=>{throw new Error('quota');};await assert.rejects(()=>repo.upsertRecurringExpense({name:'월세',amount:500000,day:1,categoryId:'housing'},'2026-09-13'),/quota/);assert.deepEqual(repo.state,before);assert.deepEqual(store.value,before);});
test('editing a cash recurring expense to card preserves recorded months and changes future entries',async()=>{const repo=new BudgetRepository(new MemoryStorage());await repo.init();await repo.upsertCard({id:'c1',name:'신한',billingDay:20,cycleRule:{type:'previous-current',startDay:15,endDay:14}});const original=await repo.upsertRecurringExpense({name:'구독',amount:12000,day:11,categoryId:'subscription',startMonth:'2026-09'},'2026-09-12');assert.equal(repo.state.transactions[0].paymentMethod,'cash');await repo.upsertRecurringExpense({id:original.id,name:'구독',amount:12000,day:11,categoryId:'subscription',paymentMethod:'card',cardId:'c1'},'2026-09-12');assert.deepEqual(repo.state.recurringExpenses[0].generatedMonths,['2026-09']);assert.equal(repo.state.recurringExpenses[0].startMonth,'2026-09');assert.equal(repo.state.transactions.length,1);assert.equal(repo.state.transactions[0].paymentMethod,'cash');await repo.materializeRecurringExpenses('2026-10-11');assert.equal(repo.state.transactions.length,2);assert.equal(repo.state.transactions[0].date,'2026-10-11');assert.equal(repo.state.transactions[0].paymentMethod,'card');assert.equal(repo.state.transactions[0].cardId,'c1');});
test('invalid recurring card is rejected without changing records',async()=>{const store=new MemoryStorage(),repo=new BudgetRepository(store);await repo.init();const before=structuredClone(repo.state);await assert.rejects(()=>repo.upsertRecurringExpense({name:'구독',amount:12000,day:11,categoryId:'subscription',paymentMethod:'card',cardId:'missing'},'2026-09-12'),/결제수단/);assert.deepEqual(repo.state,before);assert.deepEqual(store.value,before);});
test('editing an already generated fixed expense updates October forecast without rewriting the ledger',async()=>{
  const repo=new BudgetRepository(new MemoryStorage());await repo.init();
  await repo.upsertCard({id:'c1',name:'주사용 카드',billingDay:20,cycleRule:{type:'previous-current',startDay:15,endDay:14}});
  const original=await repo.upsertRecurringExpense({name:'구독',amount:12000,day:16,categoryId:'subscription',paymentMethod:'card',cardId:'c1',startMonth:'2026-09'},'2026-09-18');
  const ledger=structuredClone(repo.state.transactions);
  await repo.upsertRecurringExpense({id:original.id,name:'구독',amount:19000,day:16,categoryId:'subscription',paymentMethod:'card',cardId:'c1'},'2026-09-18');
  assert.deepEqual(repo.state.transactions,ledger);
  const projected=projectedCardTransactions(repo.state,'2026-09-18'),forecast=cardPaymentForecast(projected,repo.state.cards,'2026-09-18');
  assert.equal(forecast.nextMonth,'2026-10');assert.equal(forecast.next[0].total,19000);
  assert.equal(projected.filter(tx=>tx.recurringExpenseId===original.id).length,1);
  assert.equal(repo.state.transactions[0].amount,12000);
});
