import test from'node:test';import assert from'node:assert/strict';import{BudgetRepository}from'../assets/js/repository.js';import{defaultState}from'../assets/js/domain.js';
class MemoryStorage{constructor(value=null){this.value=value;this.saves=0;}async load(){return structuredClone(this.value);}async save(next,revision){if((this.value?.revision??0)!==revision)throw new Error('conflict');this.value=structuredClone(next);this.saves++;}}
const item={date:'2026-09-11',time:'12:00',type:'expense',amount:1200,merchant:'편의점',categoryId:'living',paymentMethod:'cash',cardId:null,source:'manual',sourceId:'',memo:'',installment:null,cancelled:false,linkedOriginal:null};
test('CRUD writes one authoritative revision at a time',async()=>{const store=new MemoryStorage(),repo=new BudgetRepository(store);await repo.init();const added=await repo.addTransaction(item);assert.equal(repo.state.revision,1);await repo.updateTransaction(added.id,{memo:'수정'});assert.equal(repo.state.transactions[0].memo,'수정');await repo.removeTransaction(added.id);assert.equal(repo.state.transactions.length,0);assert.equal(repo.state.revision,3);});
test('automatic duplicate registration is blocked',async()=>{const repo=new BudgetRepository(new MemoryStorage());await repo.init();await repo.addTransaction(item);await assert.rejects(()=>repo.addTransaction(item),/같은 거래/);assert.equal(repo.state.transactions.length,1);});
test('invalid persisted state is never automatically reset',async()=>{const store=new MemoryStorage({revision:8,transactions:[]}),repo=new BudgetRepository(store);await assert.rejects(()=>repo.init(),/항목이 없어요/);assert.equal(store.saves,0);assert.equal(store.value.revision,8);});
test('theme persistence and atomic import share normal commit path',async()=>{const repo=new BudgetRepository(new MemoryStorage(defaultState()));await repo.init();await repo.setting({theme:'green'});assert.equal(repo.state.settings.theme,'green');await repo.applyImport({transactions:[{id:'imported',...item,createdAt:'2026-09-11T00:00:00Z',updatedAt:'2026-09-11T00:00:00Z'}],importRecord:{id:'imp',kind:'test'},metaPatch:{lastNotionSync:'now'}});assert.equal(repo.state.transactions.length,1);assert.equal(repo.state.meta.lastNotionSync,'now');});
test('Notion export categories and transactions are committed atomically',async()=>{const store=new MemoryStorage(defaultState()),repo=new BudgetRepository(store);await repo.init();await repo.applyImport({categories:[{id:'notion_gift',name:'선물',kind:'expense',fixed:false}],transactions:[{id:'gift',...item,categoryId:'notion_gift',source:'notion',billingDate:'2026-10-10',createdAt:'2026-09-11T00:00:00Z',updatedAt:'2026-09-11T00:00:00Z'}]});assert.equal(repo.state.categories.at(-1).name,'선물');assert.equal(repo.state.transactions[0].billingDate,'2026-10-10');assert.equal(store.saves,1);});
test('failed import leaves both previous categories and transactions unchanged',async()=>{const store=new MemoryStorage(defaultState()),repo=new BudgetRepository(store);await repo.init();store.save=async()=>{throw new Error('disk full');};const before=structuredClone(repo.state);await assert.rejects(()=>repo.applyImport({categories:[{id:'new',name:'새 분류',kind:'expense',fixed:false}],transactions:[{id:'bad',...item,date:'broken'}]}));assert.deepEqual(repo.state,before);});
