(function(root){
'use strict';
const D=root.HaruDomain,I=root.HaruImport,{Store,ConflictError}=root.HaruStorage;
const $=s=>document.querySelector(s), clone=x=>JSON.parse(JSON.stringify(x));
const scope=root.HARU_STANDALONE?'standalone':new URL('.',location.href).pathname;
const PREFIX=`haru-page:${D.hash(scope)}:`,store=new Store({name:`haru-page-v1-${D.hash(scope)}`});
const PAGE_ID=D.id();const icons={
 arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',left:'<path d="M15 5l-7 7 7 7"/>',right:'<path d="M9 5l7 7-7 7"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',close:'<path d="M6 6l12 12M18 6L6 18"/>',check:'<path d="M5 12l4 4L19 6"/>',
 clock:'<circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="2.5" fill="var(--bg)"/><circle cx="15" cy="17" r="2.5" fill="var(--bg)"/>',
 archive:'<path d="M5 4h12a2 2 0 012 2v14H7a2 2 0 01-2-2V4zM5 16h14M9 4v8l3-2 3 2V4"/>',
 import:'<path d="M12 3v11M8 10l4 4 4-4M5 14v5h14v-5"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
 up:'<path d="M6 14l6-6 6 6"/>',down:'<path d="M6 10l6 6 6-6"/>',lock:'<rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 018 0v3"/>',
 leaf:'<path d="M5 19C2 7 10 4 20 4c0 11-7 16-13 12M6 18l8-8"/>',copy:'<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/>'};
function icon(name){const span=document.createElement('span');span.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.plus}</svg>`;return span.firstElementChild;}
function h(tag,props,...children){const el=document.createElement(tag);for(const [k,v]of Object.entries(props||{})){if(v==null)continue;if(k==='class')el.className=v;else if(k==='on')for(const [ev,fn]of Object.entries(v))el.addEventListener(ev,fn);else if(k==='style')Object.assign(el.style,v);else if(k in el&&!k.startsWith('aria'))el[k]=v;else el.setAttribute(k,String(v));}
 for(const child of children.flat(Infinity)){if(child===false||child==null)continue;el.append(child instanceof Node?child:document.createTextNode(String(child)));}return el;}
function button(text,fn,cls='secondary',props={}){return h('button',{type:'button',class:cls,on:{click:()=>Promise.resolve().then(fn).catch(showError)},...props},text);}
function field(label,control,hint){return h('label',{class:'field'},h('span',null,label),control,hint?h('small',null,hint):null);}
function rows(...els){return h('div',{class:'button-row'},...els);}
function input(type,value,props={}){return h('input',{type,value:value??'',...props});}
function sourceLabel(t){return {google:'Google',calendar:'캘린더',ticktick:'TickTick',text:'붙여넣기'}[t.source?.kind]||'';}
let prefs={theme:'paper',googleClientId:'',calendarId:'primary'};try{const p=JSON.parse(localStorage.getItem(PREFIX+'settings')||'{}');for(const k of Object.keys(prefs))if(typeof p[k]==='string')prefs[k]=p[k];}catch{}
document.documentElement.dataset.theme=prefs.theme==='night'?'night':'paper';
let current=D.ymd(),page=D.emptyDay(current),baseNote='',dirty=false,noteTimer=null,savePromise=null,loaded=false,modalFocus=null,toastTimer=null,busy=false,navToken=0;
let modalGeneration=0;let recoverables=[];let channel;try{channel=new BroadcastChannel(PREFIX+'changes');}catch{}
function saveStatus(text,error=false){$('#saveStatus').textContent=text;$('#saveStatus').classList.toggle('error',error);}
function toast(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4000);}
function showError(err){const message=err?.message||String(err);saveStatus('저장 확인 필요',true);const n=$('#notice');n.replaceChildren(h('span',null,message),button('닫기',()=>{n.hidden=true;},'text-button'));n.hidden=false;if($('#dialog').open){let inline=$('#dialogBody .dialog-error');if(!inline){inline=h('p',{class:'notice dialog-error',role:'alert'});$('#dialogBody').prepend(inline);}inline.textContent=message;inline.scrollIntoView({block:'nearest'});}}
function inform(message){toast(message);}
function announceChange(){channel?.postMessage({date:current,epoch:store.epoch});}
function draftKey(date=current){return PREFIX+'draft:'+PAGE_ID+':'+date;}
function stageDraft(){try{localStorage.setItem(draftKey(),JSON.stringify({date:current,note:$('#journal').value,base:baseNote,epoch:store.epoch,savedAt:new Date().toISOString()}));return true;}catch{saveStatus('임시 보관 불가',true);return false;}}
function clearMatchingDraft(date,note){try{const key=draftKey(date),d=JSON.parse(localStorage.getItem(key)||'null');if(d?.note===note)localStorage.removeItem(key);}catch{}}
async function flushNote(){
  clearTimeout(noteTimer);if(savePromise){await savePromise;if(dirty)return flushNote();return;}
  if(!dirty||!loaded)return;
  const date=current,text=$('#journal').value,base=baseNote;stageDraft();saveStatus('저장 중');
  savePromise=store.saveNote(date,text,base).then(r=>{if(current===date){baseNote=text;page=r.day;dirty=$('#journal').value!==text;saveStatus(dirty?'작성 중':'기기에 저장됨');}clearMatchingDraft(date,text);channel?.postMessage({date,epoch:store.epoch});}).catch(e=>{if(current===date)dirty=true;showError(e);throw e;}).finally(()=>{savePromise=null;});
  await savePromise;if(dirty)return flushNote();
}
async function guarded(fn){await flushNote();return fn();}
async function mutate(fn){if(!loaded||busy)return;busy=true;try{await flushNote();saveStatus('저장 중');const r=await store.update(current,fn);page=r.day;renderTasks();renderTimeline();saveStatus('기기에 저장됨');announceChange();return r.value;}finally{busy=false;}}
function openModal(title,body,kicker='하루, 한 장'){modalGeneration++;if(!$('#dialog').open)modalFocus=document.activeElement;$('#dialogTitle').textContent=title;$('#dialogKicker').textContent=kicker;$('#dialogBody').replaceChildren(body);if(!$('#dialog').open)$('#dialog').showModal();}
function closeModal(){modalGeneration++;$('#dialog').close();if(modalFocus?.isConnected)modalFocus.focus();}
function dateLabel(date){return new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(D.dateOf(date));}
function updateHeading(){const dt=D.dateOf(current);$('#dateEyebrow').textContent=`${dt.getFullYear()} · ${String(dt.getMonth()+1).padStart(2,'0')} / ${String(dt.getDate()).padStart(2,'0')}     ${['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'][dt.getDay()]}`;$('#dateTitle').textContent=dateLabel(current);$('#dateInput').value=current;$('#todayBtn').disabled=current===D.ymd();document.title=`${current===D.ymd()?'오늘':current} · 하루, 한 장`;}
function renderTasks(){
 const stats=D.stats(page);$('#taskCount').textContent=stats.total?`${stats.done} / ${stats.total}`:'';const c=D.conflicts(page.tasks);const list=$('#taskList');const focused=document.activeElement?.dataset?.focus;
 list.replaceChildren(...page.tasks.map(t=>{
  const check=h('button',{type:'button',class:'check-button','aria-label':`${t.title} ${t.done?'완료 취소':'완료'}`,'aria-pressed':String(t.done),disabled:!!t.movedTo,'data-focus':`check-${t.id}`,on:{click:()=>mutate(p=>{const x=p.tasks.find(x=>x.id===t.id);if(x&&!x.movedTo)x.done=!x.done;}).catch(showError)}},h('span',{class:'check-box'},t.done?icon('check'):null));
  const meta=[];if(t.movedTo)meta.push(h('span',null,`${t.movedTo.slice(5).replace('-','/')}로 옮김`));if(t.carriedFrom)meta.push(h('span',null,`${t.carriedFrom.slice(5).replace('-','/')}에서 이어온 일`));if(t.fixed)meta.push(icon('lock'));if(sourceLabel(t)&&t.source.kind!=='text')meta.push(h('span',null,sourceLabel(t)));if(t.allDay)meta.push(h('span',null,'종일'));if(t.note)meta.push(h('span',null,'메모'));
  const title=button([h('span',{class:'title-text'},t.title),meta.length?h('span',{class:'task-meta'},meta):null],()=>guarded(()=>openTask(t.id)),'task-title',{'data-focus':`title-${t.id}`});
  const time=t.movedTo?null:button([icon('clock'),t.slot?`${D.hm(t.slot.start)}–${D.hm(t.slot.start+t.slot.duration)}`:null],()=>guarded(()=>openTask(t.id,true)),`task-time ${t.slot?'scheduled':''} ${c.has(t.id)?'overlap':''}`,{'aria-label':t.slot?`${t.title} 시간 변경`:`${t.title} 시간 잡기`});
  return h('div',{class:`task ${t.done?'done':''} ${t.movedTo?'moved':''}`,'data-id':t.id},check,title,time);
 }));$('#emptyTasks').hidden=page.tasks.length>0;
 if(focused)list.querySelector(`[data-focus="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});
}
function renderTimeline(){const stats=D.stats(page),cs=D.conflicts(page.tasks);$('#scheduleSummary').replaceChildren(h('span',null,`${stats.planned}개 시간 블록`),h('span',null,`예정 ${stats.occupied>=60?`${Math.floor(stats.occupied/60)}시간 `:''}${stats.occupied%60}분`),...(cs.size?[h('span',{class:'danger'},`${cs.size}개 겹침 · 직접 조정 가능`)]:[]));
 const selected=page.tasks.filter(t=>t.slot&&!t.movedTo).sort((a,b)=>a.slot.start-b.slot.start);$('#timeEmpty').hidden=selected.length>0;
 const all=page.tasks.filter(t=>t.allDay&&!t.movedTo&&!t.slot);$('#allDayItems').replaceChildren(...(all.length?[h('p',{class:'all-day-label'},'종일 일정')]:[]),...all.map(t=>block(t,cs)));
 let first=selected.length?Math.min(7,Math.floor(selected[0].slot.start/60)):8;let last=selected.length?Math.max(20,Math.ceil(Math.max(...selected.map(t=>t.slot.start+t.slot.duration))/60)):19;last=Math.min(last,24);
 const timeline=$('#timeline'),scroll=timeline.scrollTop;timeline.replaceChildren();for(let hour=first;hour<last;hour++){const entries=selected.filter(t=>Math.floor(t.slot.start/60)===hour);const line=h('div',{class:'hour-line'},...entries.map(t=>block(t,cs)));if(!entries.length)line.append(button('+',()=>guarded(()=>newBlock(hour*60)),'add-at',{'aria-label':`${D.hm(hour*60)}에 시간 잡기`}));
   timeline.append(h('div',{class:'hour-row'},h('span',{class:'hour-label'},D.hm(hour*60)),line));}timeline.scrollTop=scroll;
}
function block(t,cs){return h('div',{class:`block ${t.fixed?'fixed':''} ${t.done?'done':''} ${cs.has(t.id)?'overlap':''}`},button([h('strong',null,t.title),h('small',null,t.slot?`${D.hm(t.slot.start)} — ${D.hm(t.slot.start+t.slot.duration)} · ${t.slot.duration}분`:'종일'),t.fixed?h('span',{class:'tag'},icon('lock'),'가져온 일정'):null],()=>guarded(()=>openTask(t.id,true)),'block-content'),button(h('span',{class:'check-box'},t.done?icon('check'):null),()=>mutate(p=>{const x=p.tasks.find(x=>x.id===t.id);if(x)x.done=!x.done;}),'check-button',{'aria-label':`${t.title} ${t.done?'완료 취소':'완료'}`}));}
async function navigate(date){if(!D.validDate(date))return;await flushNote();if(!loaded)return;const seq=++navToken;const p=await store.get(date);if(seq!==navToken)return;current=date;page=p;baseNote=p.note;dirty=false;$('#journal').value=p.note;resizeJournal();updateHeading();renderTasks();renderTimeline();saveStatus('기기에 저장됨');history.replaceState(null,'','#'+date);await renderCarry();loadRecoveries();}
function resizeJournal(){const el=$('#journal');el.style.height='auto';el.style.height=Math.max(240,el.scrollHeight)+'px';$('#journalCount').textContent=el.value.length.toLocaleString('ko-KR')+'자';}
async function renderCarry(){const el=$('#carryHint'),date=current;el.hidden=true;const y=await store.get(D.shiftDay(date,-1));if(current!==date)return;const rest=y.tasks.filter(t=>!t.done&&!t.movedTo&&!t.fixed);if(!rest.length)return;el.replaceChildren(h('span',null,`어제 남겨둔 일 ${rest.length}개`),button('선택해서 이어오기',()=>openCarry(y.date,rest),'text-button'));el.hidden=false;}
function openCarry(from,tasks){const choices=tasks.map(t=>({task:t,el:input('checkbox','',{'aria-label':t.title})}));openModal('어제의 일을 가볍게 이어와요',h('div',null,h('p',{class:'muted'},'고른 항목만 오늘로 옮깁니다. 어제에는 옮긴 흔적을 남겨요.'),...choices.map(x=>h('label',{class:'import-choice'},x.el,h('span',null,x.task.title))),rows(button('취소',closeModal),button('선택한 일 이어오기',async()=>{const ids=choices.filter(x=>x.el.checked).map(x=>x.task.id);if(!ids.length)return toast('이어올 일을 선택해 주세요.');await store.change([from,current],m=>{const a=m.get(from),b=m.get(current);for(const id of ids){const t=a.tasks.find(t=>t.id===id);if(!t||t.done||t.movedTo||t.fixed)continue;const next=D.carryTask(t,from,current);if(!next.source||!b.tasks.some(x=>x.source?.key===next.source.key))b.tasks.push(next);t.movedTo=current;t.slot=null;}});closeModal();await navigate(current);toast('선택한 일을 오늘로 옮겼어요.');announceChange();},'primary'))));}
function openTask(id,focusTime=false){const original=page.tasks.find(t=>t.id===id);if(!original)return;const t=clone(original),title=input('text',t.title,{maxLength:500}),note=h('textarea',{value:t.note,maxLength:10000,rows:3}),start=input('time',t.slot?D.hm(t.slot.start):'09:00',{step:300}),duration=input('number',t.slot?.duration||30,{min:1,max:1440,step:5,inputMode:'numeric'}),enable=input('checkbox','',{checked:!!t.slot});
 const timeFields=h('div',null,field('시작 시각',start),field('길이 (분)',duration));timeFields.className='field-row';timeFields.hidden=!enable.checked;
 enable.addEventListener('change',()=>timeFields.hidden=!enable.checked);
 const chips=h('div',{class:'chips'},...[15,30,60,90].map(n=>button(`${n}분`,()=>{duration.value=n;},'chip')));chips.hidden=!enable.checked;enable.addEventListener('change',()=>chips.hidden=!enable.checked);
 const fixed=t.fixed?h('p',{class:'import-warning'},'원본 일정의 복사본이에요. 여기서 바꿔도 원본 앱에는 반영하지 않아요.'):null;
 const body=h('div',null,fixed,field('할 일',title),h('label',{class:'import-choice'},enable,h('span',null,'시간 잡기',h('small',null,'끄면 시간만 없어지고 할 일은 그대로 남아요.'))),timeFields,chips,field('짧은 메모',note),rows(button('취소',closeModal),button('변경 저장',async()=>{
   const patch=D.task({...t,title:title.value,note:note.value,allDay:enable.checked?false:t.allDay,slot:enable.checked?D.span(D.minutes(start.value),Number(duration.value)):null});
   await mutate(p=>{const ix=p.tasks.findIndex(x=>x.id===id);if(ix<0)throw new ConflictError('다른 창에서 지워진 할 일이에요.');if(JSON.stringify(p.tasks[ix])!==JSON.stringify(original))throw new ConflictError();p.tasks[ix]=patch;});closeModal();toast('변경했어요.');
 },'primary')),h('hr',{class:'divider'}));
 const currentIndex=page.tasks.findIndex(t=>t.id===id);
 body.append(rows(button([icon('up'),' 위로'],async()=>{await mutate(p=>{const i=p.tasks.findIndex(t=>t.id===id);if(i>0)[p.tasks[i-1],p.tasks[i]]=[p.tasks[i],p.tasks[i-1]];});closeModal();},'secondary',{disabled:currentIndex===0}),button([icon('down'),' 아래로'],async()=>{await mutate(p=>{const i=p.tasks.findIndex(t=>t.id===id);if(i>=0&&i<p.tasks.length-1)[p.tasks[i],p.tasks[i+1]]=[p.tasks[i+1],p.tasks[i]];});closeModal();},'secondary',{disabled:currentIndex===page.tasks.length-1})));
 body.append(rows(button('다음 날로 보내기',async()=>{await store.move(current,id,D.shiftDay(current,1));closeModal();await navigate(current);toast('다음 날에 시간을 비워서 옮겼어요.');announceChange();},'secondary',{disabled:t.done||t.fixed||!!t.movedTo}),button('할 일 삭제',async()=>{if(!confirm('이 할 일과 붙인 시간을 지울까요? 오늘의 기록은 남아요.'))return;await mutate(p=>{const old=p.tasks.find(x=>x.id===id);if(JSON.stringify(old)!==JSON.stringify(original))throw new ConflictError();p.tasks=p.tasks.filter(x=>x.id!==id);});closeModal();toast('할 일을 지웠어요.');},'secondary danger')));
 openModal(t.movedTo?'옮긴 할 일':'할 일 다듬기',body);if(t.movedTo){enable.disabled=true;}
 if(focusTime&&!t.movedTo){enable.checked=true;timeFields.hidden=false;chips.hidden=false;start.focus();}
}
function newBlock(at=9*60){const title=input('text','',{placeholder:'집중할 일 한 가지',maxLength:500}),start=input('time',D.hm(at)),duration=input('number',30,{min:1,max:1440,step:5,inputMode:'numeric'}),candidates=page.tasks.filter(t=>!t.slot&&!t.done&&!t.movedTo);const select=h('select',null,h('option',{value:''},'새 할 일'),...candidates.map(t=>h('option',{value:t.id},t.title)));select.addEventListener('change',()=>{title.value=candidates.find(t=>t.id===select.value)?.title||'';title.disabled=!!select.value;});
 openModal('집중할 시간 한 칸',h('div',null,candidates.length?field('어떤 일에 시간을 붙일까요?',select):null,field('할 일',title),h('div',{class:'field-row'},field('시작',start),field('길이 (분)',duration)),h('div',{class:'chips'},...[15,30,60,90].map(n=>button(`${n}분`,()=>duration.value=n,'chip'))),rows(button('취소',closeModal),button('시간 잡기',async()=>{const slot=D.span(D.minutes(start.value),Number(duration.value));await mutate(p=>{if(select.value){const t=p.tasks.find(t=>t.id===select.value);if(!t||t.slot)throw new ConflictError('이 항목의 시간이 바뀌었어요. 다시 열어 주세요.');t.slot=slot;}else p.tasks.push(D.task({...D.createTask(title.value),slot}));});closeModal();toast('시간을 붙였어요.');},'primary'))));title.focus();}
function pasteTasks(){const text=h('textarea',{rows:7,placeholder:'한 줄에 하나씩 적어 주세요.\n영어 복습\n10:00-11:00 보고서 읽기',maxLength:300000});openModal('여러 줄을 한 번에',h('div',null,h('p',{class:'muted'},'빈 줄은 건너뛰어요. 09:00-09:30처럼 시간을 앞에 붙여도 좋아요.'),field('오늘 할 일',text),rows(button('취소',closeModal),button('목록에 넣기',async()=>{const parsed=I.parseText(text.value,current);if(!parsed.candidates.length)return toast('한 줄 이상 적어 주세요.');const res=await mutate(p=>D.importInto(p,parsed.candidates));closeModal();toast(`${res.added}개를 넣었어요${res.skipped?` · 중복 ${res.skipped}개는 유지`:''}.`);},'primary'))));text.focus();}
function todayMenu(){openModal('오늘 페이지',h('div',null,button('여러 줄 한 번에 넣기',pasteTasks,'secondary full'),button('오늘 페이지 텍스트 복사',async()=>{await copyText(markdown());toast('오늘 페이지를 복사했어요.');},'secondary full'),button('오늘 페이지 텍스트 파일',()=>download(`하루_${current}.txt`,markdown(),'text/plain;charset=utf-8'),'secondary full'),h('p',{class:'muted',style:{marginTop:'18px'}},'완료한 일도 그 자리에 남겨요. 과거 날짜는 위 날짜 선택이나 지난 기록에서 다시 열 수 있어요.')));}
function markdown(){return `${dateLabel(current)} (${current})\n\n오늘 할 일\n${page.tasks.map(t=>`${t.done?'✓':'□'} ${t.title}${t.slot?` (${D.hm(t.slot.start)}–${D.hm(t.slot.start+t.slot.duration)})`:''}${t.movedTo?` → ${t.movedTo}`:''}${t.note?'\n  '+t.note.replace(/\n/g,'\n  '):''}`).join('\n')}\n\n오늘의 기록\n${$('#journal').value}\n`;}
function download(name,content,type='application/json'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=h('a',{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function copyText(text){if(navigator.clipboard&&location.protocol!=='file:'){await navigator.clipboard.writeText(text);return;}const ta=h('textarea',{value:text,style:{position:'fixed',opacity:'0'}});document.body.append(ta);ta.select();if(!document.execCommand('copy')){ta.remove();throw new Error('복사가 차단됐어요. 텍스트 파일로 보관해 주세요.');}ta.remove();}
async function showArchive(){await flushNote();const days=(await store.all()).filter(d=>d.tasks.length||d.note),search=input('search','',{class:'search-input',placeholder:'날짜, 할 일, 기록 검색','aria-label':'지난 기록 검색'}),box=h('div');
 const paint=()=>{const q=search.value.trim().toLowerCase(),filtered=days.filter(d=>`${d.date} ${d.note} ${d.tasks.map(t=>t.title).join(' ')}`.toLowerCase().includes(q));box.replaceChildren(...filtered.slice(0,150).map(d=>button([h('span',{class:'archive-date'},d.date),h('span',null,h('strong',null,`${D.stats(d).done}/${D.stats(d).total} 완료`),h('small',null,d.note||d.tasks[0]?.title||'빈 페이지'))],async()=>{closeModal();await navigate(d.date);},'archive-row')),...(filtered.length===0?[h('p',{class:'muted',style:{padding:'25px 0'}},'아직 기록이 없어요. 오늘의 첫 줄부터 시작해요.')]:[]));};search.addEventListener('input',paint);paint();openModal('차곡차곡, 지난 페이지',h('div',null,search,box));}
function persistPrefs(){try{localStorage.setItem(PREFIX+'settings',JSON.stringify(prefs));}catch{throw new Error('설정을 기기에 저장하지 못했어요.');}document.documentElement.dataset.theme=prefs.theme;document.querySelector('meta[name="theme-color"]').content=prefs.theme==='night'?'#171d1b':'#f5f3ed';}
function showSettings(){
 const file=input('file','',{accept:'.json,application/json',class:'file-input','aria-label':'기록 백업 선택'});file.addEventListener('change',()=>{const f=file.files?.[0];if(!f)return;if(f.size>25*1024*1024)return showError(new Error('25MB 이하의 백업 파일을 선택해 주세요.'));f.text().then(t=>restorePreview(JSON.parse(t))).catch(showError);});
 const googleId=input('text',prefs.googleClientId,{placeholder:'…apps.googleusercontent.com',autoComplete:'off',spellcheck:false}),calendar=input('text',prefs.calendarId,{placeholder:'primary',autoComplete:'off'});
 const integration=h('details',null,h('summary',null,'Google Calendar 직접 연결 설정'),h('p',{class:'muted'},'개인 Google OAuth 클라이언트 ID가 있어야 직접 연결돼요. 이 앱이나 ChatGPT의 기존 연결이 자동 이전되지는 않아요. Client Secret이나 API 비밀키는 입력하지 마세요.'),field('공개 OAuth 클라이언트 ID',googleId),field('캘린더 ID',calendar,'기본 캘린더는 primary로 두세요.'),button('연결 설정 저장',()=>{const cid=googleId.value.trim();if(cid&&!/^[\w-]+\.apps\.googleusercontent\.com$/.test(cid))throw new Error('공개 OAuth 클라이언트 ID 형식을 확인해 주세요.');prefs.googleClientId=cid;prefs.calendarId=calendar.value.trim()||'primary';persistPrefs();toast('설정을 저장했어요. 오늘 불러오기에서 직접 연결할 수 있어요.');},'secondary full'),h('p',{class:'muted',style:{marginTop:'12px'}},`Google Cloud에서 Calendar API를 켜고 웹 OAuth 클라이언트의 승인된 JavaScript 출처에 ${location.protocol==='file:'?'배포할 HTTPS 주소':location.origin}를 등록해야 해요. 개인 테스트 앱이면 본인 계정도 테스트 사용자로 지정해 주세요.`));
 const body=h('div',null,h('div',{class:'settings-group'},h('h3',null,'페이지의 분위기'),rows(button('밝은 종이',()=>{prefs.theme='paper';persistPrefs();showSettings();},`chip ${prefs.theme==='paper'?'selected':''}`,{'aria-pressed':String(prefs.theme==='paper')}),button('조용한 밤',()=>{prefs.theme='night';persistPrefs();showSettings();},`chip ${prefs.theme==='night'?'selected':''}`,{'aria-pressed':String(prefs.theme==='night')}))),h('hr',{class:'divider'}),h('h3',null,'내 기록 보관하기'),h('p',{class:'muted'},'기록은 이 기기의 이 브라우저에만 저장돼요. 다른 기기와 자동 동기화되지 않으며, 브라우저 데이터를 지우면 없어질 수 있어요.'),button('모든 날짜 JSON 백업',async()=>{await flushNote();download(`하루_전체백업_${D.ymd()}.json`,JSON.stringify(await store.export(),null,2));toast('백업 파일을 만들었어요. 파일 앱에서 저장을 확인해 주세요.');},'secondary full'),field('백업 불러오기',file,'미리보기 후 합치기 또는 교체를 직접 선택해요.'),button('마지막 불러오기 전 기록 보관',async()=>{const b=await store.previousBackup();if(!b)return toast('아직 불러오기 전 사본이 없어요.');download('하루_불러오기전_사본.json',JSON.stringify(b,null,2));},'text-button'),h('hr',{class:'divider'}),h('h3',null,'요청할 때만 가져오기'),h('p',{class:'muted'},'Google은 설정 후 직접 조회, TickTick은 CSV·ICS·오늘 목록 붙여넣기를 지원해요. 자동 조회나 원본 수정은 하지 않아요. 직접 TickTick 계정 로그인은 이 버전에 포함하지 않았어요.'),integration,h('hr',{class:'divider'}),h('h3',null,'홈 화면에 두기'),h('p',{class:'muted'},root.HARU_STANDALONE?'이 파일은 설치 없이 실행하는 단일 파일판이에요. HTTPS 배포판에서는 홈 화면 설치와 오프라인 실행을 지원해요.':'Safari: 공유 → 홈 화면에 추가. Chrome: 메뉴 → 홈 화면에 추가 또는 앱 설치. 처음 한 번은 인터넷에 연결해 앱 파일을 받아 주세요.'),h('p',{class:'muted',style:{marginTop:'13px'}},'하루, 한 장 · 1.0.0\n서버 저장, 분석 추적, 광고가 없는 개인 플래너입니다.'));
 if(swWaiting)body.append(button('준비된 새 버전 적용',applyUpdate,'secondary full'));
 openModal('내 방식대로, 가볍게',body,'SETTINGS');
}
function restorePreview(raw){const data=D.backup(raw);openModal('백업을 불러올까요?',h('div',null,h('p',{class:'muted'},`${data.days.length}일 · 할 일 ${data.days.reduce((n,d)=>n+d.tasks.length,0)}개가 있어요. 불러오기 전 기록은 기기에 별도 사본으로 보관해요.`),h('p',{class:'import-warning'},'합치기는 같은 ID의 현재 할 일을 유지하고, 다른 메모는 구분선 뒤에 붙여요. 교체는 이 앱의 날짜별 기록을 백업 내용으로 바꿔요.'),rows(button('취소',closeModal),button('현재 기록에 합치기',()=>applyBackup(data,'merge'),'primary')),button('백업으로 전체 교체',async()=>{if(confirm('이 앱의 모든 날짜 기록을 선택한 백업으로 바꿀까요? 다른 앱은 건드리지 않아요.'))await applyBackup(data,'replace');},'secondary full danger')));}
async function applyBackup(data,mode){await flushNote();await store.import(data,mode);closeModal();await navigate(current);announceChange();toast('백업을 불러왔어요.');}
function loadRecoveries(){recoverables=[];try{for(let j=0;j<localStorage.length;j++){const key=localStorage.key(j);if(!key.startsWith(PREFIX+'draft:'))continue;try{const value=JSON.parse(localStorage.getItem(key));if(value.date!==current||typeof value.note!=='string')continue;if(value.note===page.note){localStorage.removeItem(key);j--;continue;}recoverables.push({key,value});}catch{}}}catch{}
 const n=$('#recovery');n.hidden=!recoverables.length;if(recoverables.length)n.replaceChildren(h('span',null,`아직 저장을 확인하지 못한 메모 ${recoverables.length}개가 있어요.`),button('초안 확인',showRecovery,'text-button'));}
function showRecovery(){const item=recoverables[0];if(!item)return;const v=item.value;openModal('남겨둔 초안',h('div',null,h('p',{class:'muted'},'다른 창과 충돌했거나 앱이 닫히기 전에 적은 내용일 수 있어요. 자동으로 덮어쓰지 않아요.'),field('보관된 내용',h('textarea',{value:v.note,readOnly:true,rows:8})),rows(button('초안 파일 보관',()=>download(`하루_초안_${v.date}.txt`,v.note,'text/plain;charset=utf-8')),button('현재 기록에 적용',async()=>{await flushNote();const fresh=await store.get(current);const text=(fresh.note===v.base||!fresh.note)?v.note:`${fresh.note}\n\n── 복구한 초안 ──\n${v.note}`;await store.saveNote(current,text,fresh.note);try{localStorage.removeItem(item.key);}catch{}closeModal();await navigate(current);announceChange();toast('초안을 반영했어요.');},'primary')),button('이 초안만 버리기',()=>{if(!confirm('이 초안을 버릴까요? 현재 저장된 기록은 유지돼요.'))return;try{localStorage.removeItem(item.key);}catch{}closeModal();loadRecoveries();},'text-button danger')));}
async function openImport(){await flushNote();const date=D.ymd();if(current!==date)await navigate(date);const importTicket=modalGeneration+1;
 const file=input('file','',{class:'file-input',accept:'.ics,.csv,.txt,text/calendar,text/csv,text/plain','aria-label':'오늘 자료 파일'});
 const text=h('textarea',{rows:5,maxLength:300000,placeholder:'TickTick의 오늘 목록을 복사해 붙여넣으세요.\n10:00-11:00 회의\n영어 복습'});
 file.addEventListener('change',async()=>{try{const f=file.files?.[0];if(!f)return;if(f.size>4*1024*1024)throw new Error('4MB 이하의 파일을 골라 주세요.');const content=await f.text();if(modalGeneration!==importTicket||!$('#dialog').open)return;const ext=f.name.split('.').pop().toLowerCase();const parsed=ext==='ics'?I.parseICS(content,date):ext==='csv'?I.parseCSV(content,date):I.parseText(content,date);previewImport(parsed,date);}catch(e){showError(e);toast(e.message);}});
 const google=button('Google Calendar · 연결 준비',async()=>{if(!prefs.googleClientId){showSettings();return toast('Google 직접 연결에는 본인의 공개 OAuth 클라이언트 ID가 필요해요.');}if(location.protocol==='file:')throw new Error('Google 직접 연결은 HTTPS 배포 주소에서 사용할 수 있어요.');google.disabled=true;try{await I.loadGoogle();if(modalGeneration!==importTicket||!$('#dialog').open)return;google.textContent='Google 로그인 후 오늘 조회';google.onclick=null;google.replaceWith(button('Google 로그인 후 오늘 조회',async()=>{const token=await I.authorizeGoogle(prefs.googleClientId);if(modalGeneration!==importTicket||!$('#dialog').open)return;const result=await I.fetchGoogleToday(token,date,prefs.calendarId);if(modalGeneration!==importTicket||!$('#dialog').open)return;previewImport(result,date);},'primary full'));}finally{google.disabled=false;}},'secondary full');
 openModal('오늘에 필요한 것만',h('div',null,h('p',{class:'muted'},`${date} · ${Intl.DateTimeFormat().resolvedOptions().timeZone}\n선택한 항목을 이 페이지에 복사해요. 원본 앱은 바뀌지 않아요.`),google,h('p',{class:'muted',style:{marginTop:'8px'}},prefs.googleClientId?'버튼을 눌렀을 때만 오늘 일정을 읽어요. 토큰은 저장하지 않아요.':'직접 계정 연결은 아직 설정되지 않았어요. 아래 파일·붙여넣기는 바로 사용할 수 있어요.'),h('hr',{class:'divider'}),field('TickTick CSV / 캘린더 ICS / 텍스트',file,'날짜가 있는 파일은 오늘에 해당하는 항목만 골라요. 반복 규칙이 있는 ICS 일정은 경고와 함께 제외해요.'),field('오늘 목록 붙여넣기',text),button('붙여넣은 목록 미리보기',()=>previewImport(I.parseText(text.value,date),date),'primary full'),h('p',{class:'muted',style:{marginTop:'15px'}},'오늘 목록을 직접 복사해 온 경우 날짜 없는 줄도 오늘 할 일로 봐요. 제목이 아닌 원본 ID로 중복을 막고, 기존 체크·메모는 유지해요.')),'MANUAL IMPORT');
}
function previewImport({candidates,warnings},date){const seen=new Set(page.tasks.flatMap(t=>t.source?[t.source.key]:[]));const choices=candidates.map(t=>({t,duplicate:seen.has(t.source?.key),check:input('checkbox','',{checked:!seen.has(t.source?.key),disabled:seen.has(t.source?.key)})}));const allBtn=button('새 항목 모두 선택',()=>choices.forEach(x=>{if(!x.duplicate)x.check.checked=true;}),'text-button');
 openModal(`${date.slice(5).replace('-','/')} 가져오기 미리보기`,h('div',null,h('p',{class:'muted'},`${candidates.length}개 발견 · 이미 있는 항목은 덮어쓰지 않아요.`),warnings.length?h('div',{class:'import-warning'},...warnings.slice(0,15).map(w=>h('p',null,w)),warnings.length>15?h('p',null,`그 외 ${warnings.length-15}개 경고`):null):null,allBtn,h('div',{class:'import-choices'},...choices.map(x=>h('label',{class:'import-choice'},x.check,h('span',null,x.t.title,h('small',null,`${x.duplicate?'이미 가져옴 · 현재 기록 유지':x.t.slot?`${D.hm(x.t.slot.start)}–${D.hm(x.t.slot.start+x.t.slot.duration)}`:x.t.allDay?'종일':'시간 없음'} · ${sourceLabel(x.t)}`))))),!choices.length?h('p',{class:'muted'},'가져올 오늘 항목이 없어요. 날짜와 파일 양식을 확인해 주세요.'):null,rows(button('취소',closeModal),button('선택한 항목 가져오기',async()=>{const chosen=choices.filter(x=>x.check.checked&&!x.duplicate).map(x=>x.t);if(!chosen.length)return toast('가져올 항목을 선택해 주세요.');if(current!==date)await navigate(date);const res=await mutate(p=>D.importInto(p,chosen));closeModal();toast(`${res.added}개를 가져왔어요.`);},'primary'))),'PREVIEW · NO SYNC');
}
let swWaiting=null;
async function applyUpdate(){await flushNote();if(!swWaiting)return;swWaiting.postMessage({type:'ACTIVATE_UPDATE'});}
async function setupSW(){if(root.HARU_STANDALONE||!('serviceWorker'in navigator)||!['https:','http:'].includes(location.protocol))return;try{
 const r=await navigator.serviceWorker.register('./sw.js',{scope:'./'});const waiting=()=>{if(!r.waiting)return;swWaiting=r.waiting;const n=$('#notice');n.replaceChildren(h('span',null,'새 페이지 버전이 준비됐어요. 기록을 저장하고 적용할 수 있어요.'),button('새 버전 적용',applyUpdate,'text-button'));n.hidden=false;};waiting();r.addEventListener('updatefound',()=>{const s=r.installing;s?.addEventListener('statechange',()=>{if(s.state==='installed'&&navigator.serviceWorker.controller)waiting();});});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(swWaiting&&!reloading&&!dirty){reloading=true;location.reload();}});
 }catch{toast('오프라인 설치를 준비하지 못했어요. 온라인에서는 계속 사용할 수 있어요.');}}
function bind(){for(const [sel,name]of Object.entries({'#archiveBtn':'archive','#settingsBtn':'settings','#prevDay':'left','#nextDay':'right','#moreTasks':'more','#addBlock':'plus','#dialogClose':'close'}))$(sel).append(icon(name));$('#quickForm .add-button').append(icon('arrow'));$('#importBtn').append(icon('import'),document.createTextNode('오늘 불러오기'));$('#journal').placeholder='정리되지 않은 생각도 괜찮아요.\n오늘을 여기에 남겨두세요.';
 $('#buildText').textContent='HARU · 1.0';
 $('#quickForm').addEventListener('submit',async e=>{e.preventDefault();const el=$('#quickTitle'),value=el.value;if(!value.trim()||busy||el.dataset.composing==='1')return;try{await mutate(p=>D.addTasks(p,[value]));if(el.value===value)el.value='';el.focus();}catch(err){showError(err);}});
 $('#quickTitle').addEventListener('compositionstart',e=>e.target.dataset.composing='1');$('#quickTitle').addEventListener('compositionend',e=>{setTimeout(()=>e.target.dataset.composing='0',0);});$('#quickTitle').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.isComposing||e.keyCode===229||e.target.dataset.composing==='1'))e.preventDefault();});
 $('#journal').addEventListener('input',()=>{if(!loaded)return;dirty=true;resizeJournal();stageDraft();saveStatus('작성 중');clearTimeout(noteTimer);noteTimer=setTimeout(()=>flushNote().catch(()=>{}),500);});
 $('#journal').addEventListener('blur',()=>flushNote().catch(()=>{}));
 const handler=(sel,fn)=>$(sel).addEventListener('click',()=>Promise.resolve().then(fn).catch(showError));
 handler('#prevDay',()=>navigate(D.shiftDay(current,-1)));handler('#nextDay',()=>navigate(D.shiftDay(current,1)));handler('#todayBtn',()=>navigate(D.ymd()));handler('.brand',()=>navigate(D.ymd()));$('.brand').addEventListener('click',e=>e.preventDefault());
 $('#dateInput').addEventListener('change',e=>navigate(e.target.value).catch(showError));handler('#settingsBtn',()=>guarded(showSettings));handler('#archiveBtn',showArchive);handler('#importBtn',openImport);handler('#addBlock',()=>guarded(()=>newBlock()));handler('#moreTasks',()=>guarded(todayMenu));handler('#pasteBtn',()=>guarded(pasteTasks));handler('#dialogClose',closeModal);
 $('#dialog').addEventListener('click',e=>{if(e.target!==$('#dialog'))return;const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();});
 $('#dialog').addEventListener('cancel',e=>{e.preventDefault();closeModal();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!e.isComposing&&$('#dialog').open){e.preventDefault();e.stopPropagation();closeModal();}},true);
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{$('.workspace').dataset.mobile=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
 addEventListener('beforeunload',e=>{if(dirty||savePromise){stageDraft();e.preventDefault();e.returnValue='';}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&dirty){stageDraft();flushNote().catch(()=>{});}});
 addEventListener('online',()=>toast('다시 온라인이에요.'));addEventListener('offline',()=>toast('오프라인이에요. 이 기기에 계속 기록할 수 있어요.'));
 if(channel)channel.onmessage=async e=>{if(e.data.epoch!==store.epoch){showError(new ConflictError('다른 창에서 기록을 불러왔어요. 현재 메모를 보관한 뒤 새로고침해 주세요.'));return;}if(e.data.date!==current)return;if(dirty||savePromise){showError(new ConflictError());return;}try{await navigate(current);}catch(err){showError(err);}};
}
async function init(){bind();try{await store.init();loaded=true;const hash=location.hash.slice(1);await navigate(D.validDate(hash)?hash:D.ymd());await setupSW();}catch(e){loaded=false;$('#quickTitle').disabled=true;$('#journal').disabled=true;showError(new Error(`기록을 읽지 못했어요. 초기화하지 않았어요. ${e.message}`));}}
root.HaruApp={store,get page(){return page;},get current(){return current;},flushNote,navigate};
init();
})(globalThis);
