import{chromium}from'playwright';import assert from'node:assert/strict';import{mkdir,writeFile,readFile}from'node:fs/promises';import{makeServer}from'../server/index.mjs';
const dir=new URL('../test-results/',import.meta.url);await mkdir(dir,{recursive:true});const server=makeServer({});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/sip/';const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,locale:'ko-KR',timezoneId:'Asia/Seoul'});const page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const check=name=>{checks.push(name);console.log('PASS '+name);};
async function record(p,title,trip='2026 일본 여행',note='비 오던 교토에서 가족과 함께 마셨다.'){await p.locator('[data-act=new]').first().click();await p.locator('#record-form [name=title]').fill(title);await p.locator('[name=date]').fill('2026-09-20');await p.locator('[name=note]').fill(note);await p.locator('[name=trip]').fill(trip);await p.locator('[name=visitCountry]').fill('일본');await p.locator('[name=city]').fill('교토');await p.locator('[name=rating]').fill('4.5');await p.locator('[name=tags]').fill('여행, 가족');const picking=p.waitForEvent('filechooser');await p.locator('[data-act=editor-photo]').click();await (await picking).setFiles(new URL('../assets/icon-180.png',import.meta.url).pathname);await p.locator('.photo-strip img').waitFor();assert.equal(await p.locator('[name=tags]').inputValue(),'여행, 가족');await p.locator('#record-form [type=submit]').click();await p.waitForFunction(()=>!document.querySelector('#sheet').open);}
const svg=await readFile(new URL('../assets/icon.svg',import.meta.url),'utf8');
for(const size of [180,192,512]){const imagePage=await context.newPage();await imagePage.setViewportSize({width:size,height:size});await imagePage.setContent('<style>html,body{margin:0;padding:0;background:transparent}</style>'+svg.replace('width="512"',`width="${size}"`).replace('height="512"',`height="${size}"`));await imagePage.screenshot({path:new URL(`../assets/icon-${size}.png`,import.meta.url).pathname,omitBackground:true});await imagePage.close();}
try{
 await page.goto(base);await page.waitForLoadState('networkidle');await page.locator('[data-act=new]').first().waitFor();assert.equal(await page.locator('.bottle-card').count(),0);check('empty start without sample pollution');
 await record(page,'교토의 레드');assert.equal(await page.locator('.bottle-card').count(),1);check('manual memory saves to real IndexedDB');check('photo attachment preserves tags and typed form values');await page.reload();await page.locator('.bottle-card').waitFor();check('record survives reload');
 await page.locator('.bottle-card').first().click();await page.locator('[data-act=again]').click();await page.locator('#record-form [name=note]').fill('두 번째 만남은 더 산뜻했다.');await page.locator('#record-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#sheet').open);assert.equal(await page.locator('.bottle-card').count(),1);check('same bottle keeps two separate memories');
 await page.locator('[data-tab=search]').click();await page.locator('#search-form [name=query]').fill('지난 일본 여행에서 마셨던 와인은');await page.locator('#search-form [type=submit]').click();assert.equal(await page.locator('.note-card').count(),1);check('natural phrase finds actual trip memories');await page.screenshot({path:new URL('search-mobile.png',dir).pathname,fullPage:true});
 await page.locator('.note-card').first().click();await page.locator('[data-act=edit]').click();await page.locator('[name=note]').fill('수정해서 저장한 기억');await page.locator('#record-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#sheet').open);await page.reload();await page.locator('[data-tab=notes]').click();assert.ok((await page.locator('main').textContent()).includes('수정해서 저장한 기억'));check('editing preserves text after reload');
 await page.locator('[data-act=new]').first().click();await page.locator('[name=title]').fill('초안 복구 라벨');await page.locator('[name=note]').fill('저장하기 전 작성 중');await page.locator('[name=tags]').fill('초안, 여행');await page.waitForTimeout(800);await page.reload();await page.locator('[data-act=recover]').click();assert.equal(await page.locator('[name=note]').inputValue(),'저장하기 전 작성 중');assert.equal(await page.locator('[name=tags]').inputValue(),'초안, 여행');check('tagged draft is restored after interrupted editing');await page.locator('#record-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#sheet').open);
 await page.locator('[data-tab=collection]').click();await page.locator('[data-act=new]').first().click();await page.locator('[name=title]').fill('오래된 창');await page.locator('[name=note]').fill('충돌에도 남아야 하는 문장');const page2=await context.newPage();await page2.goto(base);await record(page2,'다른 창의 새 기록');await page.locator('#record-form [type=submit]').click();await page.locator('#record-error').filter({hasText:'다른 창'}).waitFor();assert.equal(await page.locator('[name=note]').inputValue(),'충돌에도 남아야 하는 문장');check('cross-tab revision conflict preserves editor and stored data');await page2.close();page.on('dialog',d=>d.accept(d.type()==='prompt'?'교체':undefined));await page.locator('#sheet-close').click();await page.reload();await page.locator('[data-tab=collection]').click();
 await page.locator('[data-act=capture]').first().click();await page.locator('details summary').click();await page.locator('[name=aiJson]').fill(JSON.stringify({records:[{bottle:{title:'스캔으로 정리한 화이트',kind:'wine'},tasting:{trip:'일본 여행',visitCountry:'일본',note:'노트의 원래 문장'},transcription:'원문 보존',warnings:['빈티지 판독 확인']}]}));await page.locator('[data-act=parse-ai]').click();assert.ok((await page.locator('#sheet-body').textContent()).includes('빈티지 판독 확인'));await page.locator('#scan-preview [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#sheet').open);check('manual AI JSON goes through review and atomic save');
 await page.locator('[data-tab=collection]').click();await page.locator('[data-act=capture]').first().click();await page.locator('[name=scanText]').fill('시음 노트 테스트');await page.locator('#analyze-scan').click();assert.ok((await page.locator('#scan-error').textContent()).includes('동의'));await page.locator('#scan-consent').check();await page.locator('#analyze-scan').click();await page.locator('#scan-error').filter({hasText:'연결'}).waitFor();check('AI requires consent and never pretends to be connected');await page.locator('#sheet-close').click();
 await page.locator('[data-tab=settings]').click();await page.locator('[data-setting=accent][data-value=blue]').click();await page.waitForFunction(()=>document.body.dataset.accent==='blue');await page.locator('[data-setting=background][data-value=dark]').click();await page.waitForFunction(()=>document.body.dataset.background==='dark');await page.reload();await page.locator('[data-tab=settings]').waitFor();assert.equal(await page.locator('body').getAttribute('data-accent'),'blue');assert.equal(await page.locator('body').getAttribute('data-background'),'dark');check('theme changes persist');await page.locator('[data-setting=accent][data-value=red]').click();await page.waitForFunction(()=>document.body.dataset.accent==='red');await page.locator('[data-setting=background][data-value=cream]').click();await page.waitForFunction(()=>document.body.dataset.background==='cream');
 const dl=page.waitForEvent('download');await page.locator('[data-act=export]').click();const download=await dl,file=new URL('roundtrip.json',dir).pathname;await download.saveAs(file);const backup=JSON.parse(await readFile(file,'utf8'));assert.ok(backup.tastings.length>=5);assert.ok(!JSON.stringify(backup).includes('apiKey'));check('full backup contains real records without credentials');
 const withoutCover=backup.bottles.find(b=>!b.cover),withCover=backup.bottles.find(b=>b.cover);assert.ok(withoutCover&&withCover);const pack={app:'sip-cover-pack',schema:1,items:[{id:withoutCover.id,title:withoutCover.title,cover:withCover.cover},{id:withCover.id,title:withCover.title,cover:withCover.cover}]};const coverChooser=page.waitForEvent('filechooser');await page.locator('[data-act=import-covers]').click();await (await coverChooser).setFiles({name:'covers.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pack))});await page.locator('#cancel-cover-pack').click();let coverState=await page.evaluate(async()=>{const {JournalStore}=await import('./assets/storage.js?v=1.2.1');return (await new JournalStore().init()).bottles;});assert.equal(coverState.find(b=>b.id===withoutCover.id).cover,'');check('cancelled cover pack leaves every record unchanged');const coverChooser2=page.waitForEvent('filechooser');await page.locator('[data-act=import-covers]').click();await (await coverChooser2).setFiles({name:'covers.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pack))});assert.match(await page.locator('#sheet-body').textContent(),/빈 사진에 추가 1개/);await page.locator('#apply-cover-pack').click();await page.waitForFunction(()=>!document.querySelector('#sheet').open);await page.reload();coverState=await page.evaluate(async()=>{const {JournalStore}=await import('./assets/storage.js?v=1.2.1');return (await new JournalStore().init());});assert.equal(coverState.bottles.find(b=>b.id===withoutCover.id).cover,withCover.cover);assert.equal(coverState.bottles.find(b=>b.id===withCover.id).cover,withCover.cover);assert.deepEqual(coverState.tastings,backup.tastings);check('cover-only import survives reload without changing notes or existing photos');
 await page.locator('[data-tab=collection]').click();for(const width of[320,390,768,1024]){await page.setViewportSize({width,height:844});const size=await page.evaluate(()=>({w:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert.ok(size.scroll<=size.w+1,'horizontal overflow '+width);check('responsive collection '+width+'px');}await page.setViewportSize({width:390,height:844});await page.screenshot({path:new URL('collection-mobile.png',dir).pathname,fullPage:true});await page.locator('[data-tab=notes]').click();await page.screenshot({path:new URL('notes-mobile.png',dir).pathname,fullPage:true});
 await page.evaluate(async()=>{await caches.open('budget-test-preserve');await caches.open('workout-test-preserve');await navigator.serviceWorker.ready;});await page.waitForTimeout(1000);await context.setOffline(true);await page.reload();await page.locator('.note-card').first().waitFor();assert.ok(await page.locator('.note-card').count()>0);check('offline reload uses actual service worker and IndexedDB');const keys=await page.evaluate(()=>caches.keys());assert.ok(keys.includes('budget-test-preserve')&&keys.includes('workout-test-preserve'));check('other app caches remain untouched');await context.setOffline(false);
 const stalePage=await context.newPage();await stalePage.goto(base);await stalePage.evaluate(async()=>{const {JournalStore}=await import('./assets/storage.js?v=1.2.1');window.staleStore=new JournalStore();await window.staleStore.init();});
 await page.evaluate(async()=>{localStorage.setItem('reading:test-preserve','present');await new Promise((resolve,reject)=>{const r=indexedDB.open('reading-sip-preserve',1);r.onupgradeneeded=()=>r.result.createObjectStore('books');r.onsuccess=()=>{r.result.close();resolve();};r.onerror=()=>reject(r.error);});});
 await page.locator('[data-tab=settings]').click();await page.locator('[data-act=reset]').click();await page.locator('#cancel-reset').click();assert.ok((await page.evaluate(async()=>{const {JournalStore}=await import('./assets/storage.js?v=1.2.1');return (await new JournalStore().init()).bottles.length;}))>0);check('cancelled reset leaves existing records intact');
 await page.locator('[data-act=reset]').click();await page.locator('#reset-form input').fill('초기화');await page.locator('#reset-form [type=submit]').click();await page.locator('[data-tab=collection]').waitFor();assert.equal(await page.locator('.bottle-card').count(),0);const afterReset=await page.evaluate(async()=>{const {JournalStore}=await import('./assets/storage.js?v=1.2.1');const s=new JournalStore();await s.init();return {state:s.state,previous:await s.get('kv','previous'),draft:await s.getDraft(),reading:localStorage.getItem('reading:test-preserve'),cache:await caches.keys()};});assert.equal(afterReset.state.bottles.length,0);assert.equal(afterReset.state.tastings.length,0);assert.equal(afterReset.previous,undefined);assert.equal(afterReset.draft,undefined);assert.equal(afterReset.reading,'present');assert.ok(afterReset.cache.includes('budget-test-preserve'));check('confirmed reset removes only SIP records and drafts');
 const readingPreserved=await page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('reading-sip-preserve');r.onsuccess=()=>{resolve(r.result.objectStoreNames.contains('books'));r.result.close();};r.onerror=()=>reject(r.error);}));assert.equal(readingPreserved,true);check('reading IndexedDB remains after SIP reset');
 const staleWrites=await stalePage.evaluate(async()=>{const s=window.staleStore;return Promise.allSettled([s.save(structuredClone(s.state)),s.saveDraft({mode:'editor',note:'old'})]).then(results=>results.map(r=>r.status==='rejected'&&r.reason.name==='ConflictError'));});assert.deepEqual(staleWrites,[true,true]);await stalePage.close();await page.reload();await page.locator('[data-tab=collection]').waitFor();assert.equal(await page.locator('.bottle-card').count(),0);check('stale tab cannot restore reset data after reload');
await page.locator('[data-tab=settings]').click();const importChooser=page.waitForEvent('filechooser');await page.locator('[data-act=import]').click();await (await importChooser).setFiles({name:'journal.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#replace-import').click();await page.waitForFunction(()=>!document.querySelector('#sheet').open);await page.reload();await page.locator('[data-tab=collection]').click();assert.ok(await page.locator('.bottle-card').count()>0);check('private archive replacement survives reload after reset');
 await page.evaluate(async()=>{const {JournalStore}=await import('./assets/storage.js?v=1.2.1');const s=new JournalStore();await s.init();await s.transaction('kv','readwrite',kv=>{kv.put({broken:true},'state');});});await page.reload();await page.locator('[data-act=reset]').waitFor();assert.ok((await page.locator('main').textContent()).includes('자동 초기화하지 않았습니다'));await page.locator('[data-act=reset]').click();await page.locator('#reset-form input').fill('초기화');await page.locator('#reset-form [type=submit]').click();await page.locator('[data-tab=collection]').waitFor();assert.equal(await page.locator('.bottle-card').count(),0);check('corrupt saved state can be explicitly reset from recovery screen');
 assert.deepEqual(errors,[]);check('no uncaught browser JavaScript errors');await writeFile(new URL('browser-results.json',dir),JSON.stringify({passed:checks.length,checks,errors},null,2));
}catch(e){await page.screenshot({path:new URL('failure.png',dir).pathname,fullPage:true}).catch(()=>{});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}

await import("./family-browser.mjs");
