import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import vm from'node:vm';
import{emptyState,bottle,tasting,putExperience,removeExperience,validateState,mergeBackup,parseAiDraft,validDate,searchExperiences,safeUrl,image,summary,esc}from'../assets/domain.js';
function fixture(){let s=emptyState();const entries=[['A','wine','日本','京都','日本旅行2025','2025-08-10'],['A','wine','일본','교토','2026 일본 여행','2026-09-12'],['B','whisky','일본','도쿄','2026 일본 여행','2026-09-14'],['일본산 와인','wine','한국','서울','','2026-09-19']];for(const [title,kind,visitCountry,city,trip,date]of entries)s=putExperience(s,{title,kind,country:'일본'},{date,visitCountry,city,trip,note:'함께한 저녁',rating:4,tags:['가족']});return s;}
test('same label keeps multiple independent experiences',()=>{const s=fixture();assert.equal(s.bottles.length,3);assert.equal(s.tastings.length,4);const b=s.bottles.find(b=>b.title==='A');assert.equal(s.tastings.filter(t=>t.bottleId===b.id).length,2);});
test('editing one memory does not remove other memories',()=>{const s=fixture(),t=s.tastings[0],b=s.bottles.find(b=>b.id===t.bottleId);const out=putExperience(s,b,{...t,note:'새로운 문장'},{existingTastingId:t.id});assert.equal(out.tastings.length,4);assert.equal(out.tastings[0].note,'새로운 문장');assert.equal(s.tastings[0].note,'함께한 저녁');});
test('delete is limited to one memory and preserves bottle',()=>{const s=fixture(),out=removeExperience(s,s.tastings[0].id);assert.equal(out.tastings.length,3);assert.equal(out.bottles.length,3);});
test('visiting Japan is different from Japanese origin',()=>{const r=searchExperiences(fixture(),'일본 와인');assert.equal(r.rows.length,2);assert.ok(r.rows.every(x=>x.b.title==='A'));});
test('last Japan trip selects most recent matching trip',()=>{const r=searchExperiences(fixture(),'지난 일본 여행에서 마셨던 와인은');assert.equal(r.rows.length,1);assert.equal(r.rows[0].t.trip,'2026 일본 여행');});
test('empty search includes notes across all years',()=>assert.equal(searchExperiences(fixture()).rows.length,4));
test('year and rating filters are deterministic',()=>{assert.equal(searchExperiences(fixture(),'',{year:'2025'}).rows.length,1);assert.equal(searchExperiences(fixture(),'',{minRating:4.5}).rows.length,0);});
test('multiple terms search the original note too',()=>{const s=fixture();s.tastings[0].originalText='호텔 창가에서 붉은 과일 향';assert.equal(searchExperiences(s,'호텔 붉은').rows.length,1);});
test('backup preserves photos, source text and notes',()=>{const s=fixture(),p='data:image/png;base64,YQ==';s.tastings[0].photos=[p];s.tastings[0].originalText='원문 보존';const out=validateState(JSON.parse(JSON.stringify(s)));assert.deepEqual(out,s);});
test('backup only permits journal schema and rejects broken relations',()=>{assert.throws(()=>validateState({}),/백업 형식/);const s=fixture();s.tastings[0].bottleId='missing';assert.throws(()=>validateState(s),/연결/);});
test('duplicate IDs are rejected rather than silently merged',()=>{const s=fixture();s.tastings.push(s.tastings[0]);assert.throws(()=>validateState(s),/중복/);});
test('merge preserves local edits on same id',()=>{const s=fixture(),incoming=structuredClone(s);incoming.tastings[0].note='다른 기기';const out=mergeBackup(s,incoming);assert.equal(out.tastings.length,4);assert.equal(out.tastings[0].note,'함께한 저녁');});
test('credentials and unknown properties do not enter backups',()=>{const s=fixture();s.apiKey='secret';s.settings.token='secret';s.tastings[0].token='secret';assert.ok(!JSON.stringify(validateState(s)).includes('secret'));});
test('dates validate leap year and preserve unknown date',()=>{assert.equal(validDate('2024-02-29'),true);assert.equal(validDate('2025-02-29'),false);assert.equal(validDate(''),true);});
test('unknown scanned date stays unknown rather than today',()=>{const [r]=parseAiDraft({records:[{bottle:{title:'기억',kind:'wine'},tasting:{},transcription:'어느 여름',warnings:['연도 불명']}]});assert.equal(r.tasting.date,'');assert.equal(r.tasting.originalText,'어느 여름');assert.deepEqual(r.tasting.aiWarnings,['연도 불명']);});
test('scan rejects malformed JSON and too many items',()=>{assert.throws(()=>parseAiDraft('hello'));assert.throws(()=>parseAiDraft({records:Array(21).fill({})}));});
test('scan accepts fenced JSON and multiple notes',()=>{const a=JSON.stringify({records:[{bottle:{title:'A'}},{bottle:{title:'B'}}]});assert.equal(parseAiDraft('```json\n'+a+'\n```').length,2);});
test('AI cannot supply fake reviews or executable image URLs',()=>{const [r]=parseAiDraft({records:[{bottle:{title:'A',cover:'https://evil.example/x'},tasting:{sources:[{url:'https://evil.example'}],webSummary:'fake'}}]});assert.equal(r.bottle.cover,'');assert.equal(r.tasting.webSummary,'');assert.equal(r.tasting.sources.length,0);assert.throws(()=>image('javascript:alert(1)'));});
test('malformed numeric values and invalid dates are rejected',()=>{assert.throws(()=>bottle({title:'A',abv:1000}));assert.throws(()=>tasting({bottleId:'a',rating:6}));assert.throws(()=>tasting({bottleId:'a',date:'2026-02-30'}));});
test('unsafe source links are rejected and strings are escaped',()=>{assert.equal(safeUrl('javascript:alert(1)'),'');assert.equal(safeUrl('https://a:b@example.com'),'');assert.equal(esc('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');});
test('statistics count notes and unique labels, not alcohol amounts',()=>{const s=summary(fixture());assert.equal(s.bottles,3);assert.equal(s.notes,4);assert.equal(s.average,4);});
test('cache deletion is strictly journal-only',async()=>{const code=await readFile(new URL('../sw.js',import.meta.url),'utf8'),handlers={},deleted=[],ctx={self:{registration:{scope:'https://example.com/code/sip/'},clients:{claim:async()=>{}},addEventListener:(n,f)=>handlers[n]=f},caches:{keys:async()=>['sip-journal-old','sip-journal-v1.1.0','budget-pwa-x','workout-log-x','bookshelf-x'],delete:async k=>deleted.push(k)}};vm.runInNewContext(code,ctx);let promise;handlers.activate({waitUntil:p=>promise=p});await promise;assert.deepEqual(deleted,['sip-journal-old']);});
test('precache includes every runtime dependency',async()=>{const code=await readFile(new URL('../sw.js',import.meta.url),'utf8'),ctx={self:{addEventListener(){}}};vm.runInNewContext(code+';this.assets=ASSETS',ctx);for(const name of['app.js?v=1.1.0','domain.js?v=1.1.0','ui.js?v=1.1.0','storage.js?v=1.1.0','api.js?v=1.1.0'])assert.ok(ctx.assets.includes('./assets/'+name));});
test('service worker does not cache authentication endpoints',async()=>{const code=await readFile(new URL('../sw.js',import.meta.url),'utf8'),handlers={},ctx={URL,self:{registration:{scope:'https://example.com/code/sip/'},addEventListener:(n,f)=>handlers[n]=f}};vm.runInNewContext(code,ctx);for(const url of['https://example.com/code/sip/api/session','https://example.com/code/budget/','https://api.openai.com/v1/responses'])handlers.fetch({request:{method:'GET',url},respondWith(){assert.fail('unrelated request intercepted');}});});

test('repeated import preserves an existing cover and label text',()=>{let s=putExperience(emptyState(),{title:'A',kind:'wine',cover:'data:image/png;base64,YQ==',labelText:'원래 라벨'},{date:'2026-09-20'});s=putExperience(s,{title:'A',kind:'wine'},{date:'2026-09-21'});assert.equal(s.bottles[0].cover,'data:image/png;base64,YQ==');assert.equal(s.bottles[0].labelText,'원래 라벨');});
test('Google suggestions are isolated from the parent application',async()=>{const {suggestionsFrame}=await import('../assets/ui.js');const html=suggestionsFrame('<script>parent.localStorage.clear()</script>');assert.ok(html.includes('sandbox="allow-popups allow-popups-to-escape-sandbox"'));assert.ok(!html.includes('allow-scripts'));assert.ok(!html.includes('allow-same-origin'));assert.ok(html.includes('&lt;script&gt;'));});

test('editor accepts string tags from a restored draft',async()=>{const {editor}=await import('../assets/ui.js');const html=editor({title:'A',kind:'wine'},{tags:'여행, 가족',photos:[]});assert.ok(html.includes('여행, 가족'));});
