// Actual browser + HTTP + IndexedDB + cookies; only the upstream OpenAI service is mocked.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { createServer } from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { makeServer } from '../server/index.mjs';
const probe = createServer(); await new Promise(r => probe.listen(0, '127.0.0.1', r)); const port = probe.address().port; await new Promise(r => probe.close(r));
const origin = 'http://127.0.0.1:' + port, base = origin + '/sip/', dir = await mkdtemp(path.join(os.tmpdir(), 'sip-browser-family-'));
const env = { SIP_PUBLIC_ORIGIN: origin, SIP_MASTER_KEY: randomBytes(32).toString('base64'), SIP_FAMILY_CODE: 'browser-fixture-code-for-family-only', SIP_ALLOW_HTTP_DEV: '1', SIP_DATA_DIR: dir, OPENAI_API_KEY: 'test-key-never-reach-real-openai' };
let behavior = 'success', release = null, calls = [];
const response = (text, annotations = []) => Response.json({ status: 'completed', output: [{ type: 'message', content: [{ type: 'output_text', text, annotations }] }] });
const fake = async (url, opts) => {
  const body = JSON.parse(opts.body); calls.push(body);
  if (behavior === 'failure') return new Response('{"error":"private-secret"}', { status: 429 });
  if (behavior === 'delayed') await new Promise(r => { release = r; });
  if (body.tools) return response('웹 자료에 근거한 평가 [1]', [{ type: 'url_citation', title: '모의 웹 출처', url: 'https://example.com/tasting', start_index: 16, end_index: 19 }]);
  if (body.input === 'Reply with only OK.') return response('OK');
  return response(JSON.stringify({ records: [{ bottle: { title: '일본 여행의 레드', kind: 'wine', producer: '테스트 생산자', vintage: '2020' }, tasting: { date: '2026-09-20', visitCountry: '일본', trip: '2026 일본 여행', venue: '교토', note: '노트에 적은 개인적인 기억' }, transcription: '원문을 읽었다는 모의 응답', warnings: [] }] }));
};
const server = makeServer(env, fake); await new Promise(r => server.listen(port, '127.0.0.1', r));
const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined, args: ['--no-sandbox'] });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: 'ko-KR' });
const page = await context.newPage(), errors = [], checks = [], resultDir = new URL('../test-results/', import.meta.url);
await mkdir(resultDir, { recursive: true }); page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
const pass = name => { checks.push(name); console.log('PASS shared-api ' + name); };
try {
  await page.goto(base + '#settings');
  await page.locator('[data-act=connect]').waitFor();
  await page.locator('#family-status').filter({ hasText: '가족 이용 코드' }).waitFor();
  await page.waitForLoadState('networkidle');
  assert.equal(await page.locator('[data-setting=provider]').count(), 0);
  assert.equal(calls.length, 0); pass('settings has no provider/account/key selection and makes no paid calls');
  await page.locator('[data-act=connect]').click();
  await page.locator('#family-form [name=name]').fill('가족 아이패드');
  await page.locator('#family-form [name=code]').fill(env.SIP_FAMILY_CODE);
  await page.locator('#family-form [type=submit]').click(); await page.waitForFunction(() => !document.querySelector('#sheet').open);
  await page.locator('#family-status').filter({ hasText: '아직 실제 응답' }).waitFor();
  await page.reload(); await page.locator('.advanced-settings').evaluate(el=>el.open=true); await page.locator('[data-act=check-ai]:not(:disabled)').waitFor();
  assert.equal(calls.length, 0); pass('one family approval survives reload, not misreported as provider success');
  await page.locator('[data-act=check-ai]').click(); await page.locator('#family-status').filter({ hasText: 'OpenAI 응답 확인' }).waitFor();
  assert.equal(calls.length, 1); pass('explicit connection check calls gateway and marks confirmed only after response');
  await page.screenshot({ path: new URL('family-settings-mobile.png', resultDir).pathname, fullPage: true });
  await page.locator('[data-tab=records]').click(); await page.locator('[data-act=capture]').click();
  const select = page.waitForEvent('filechooser'); await page.locator('[data-act=scan-files]').click(); await (await select).setFiles(new URL('../assets/icon-180.png', import.meta.url).pathname);
  await page.locator('#scan-photos img').waitFor(); await page.locator('[name=scanText]').fill('내가 적은 PRIVATE 여행 노트');
  await page.locator('#analyze-scan').click(); assert.equal(calls.length, 1); await page.locator('#scan-error').filter({ hasText: '동의' }).waitFor();
  await page.locator('#scan-consent').check(); await page.locator('#analyze-scan').click();
  await page.locator('#scan-preview').waitFor(); assert.equal(calls.length, 2); assert.equal(await page.locator('.note-card').count(), 0);
  pass('photos require consent and result stays a preview until save');
  await page.locator('#scan-preview [type=submit]').click(); await page.waitForFunction(() => !document.querySelector('#sheet').open);
  await page.reload(); await page.locator('.note-card').first().waitFor(); pass('analysed note persists through actual IndexedDB reload');
  await page.locator('.note-card').first().click(); await page.locator('[data-act=open-bottle]').click(); await page.locator('[data-act=reviews]').click();
  await page.locator('a', { hasText: '모의 웹 출처' }).waitFor(); assert.equal(calls.length, 3); assert.ok(!JSON.stringify(calls.at(-1)).includes('PRIVATE'));
  await page.locator('[data-act=reviews]').click(); await page.waitForTimeout(250); assert.equal(calls.length, 3); pass('web evaluation is opt-in, excludes notes and reuses cached result');
  await page.locator('#sheet-close').click(); await page.locator('[data-tab=records]').click(); await page.locator('[data-act=capture]').click();
  await page.locator('[name=scanText]').fill('실패해도 남아야 하는 긴 기억'); await page.locator('#scan-consent').check(); behavior = 'failure';
  await page.locator('#analyze-scan').click(); await page.locator('#scan-error').filter({ hasText: '한도' }).waitFor();
  assert.equal(await page.locator('[name=scanText]').inputValue(), '실패해도 남아야 하는 긴 기억'); assert.equal(calls.length, 4);
  await page.waitForTimeout(200); assert.equal(calls.length, 4); pass('quota errors keep typed notes, no fallback and no automatic retry');
  behavior = 'delayed'; await page.locator('#analyze-scan').click(); await page.waitForFunction(() => document.querySelector('#analyze-scan').disabled);
  while (!release) await new Promise(r => setTimeout(r, 5)); await page.locator('#sheet-close').click(); await page.waitForFunction(() => !document.querySelector('#sheet').open); release(); await page.waitForTimeout(200);
  assert.equal(await page.locator('#scan-preview').count(), 0); assert.equal(await page.locator('#sheet').evaluate(el => el.open), false); pass('late AI response cannot reopen a closed scan or silently store records');
  behavior = 'success';
  const cookies = await context.cookies(); const approved = cookies.find(c => c.name === 'sip_family_dev'); assert.ok(approved?.httpOnly && approved.sameSite === 'Strict');
  const stored = await page.evaluate(async () => {
    const raw = localStorage.length ? JSON.stringify(localStorage) : '';
    const { JournalStore } = await import('./assets/storage.js?v=1.3.0'); const store = new JournalStore(); return raw + JSON.stringify(await store.init()) + JSON.stringify(await store.getDraft());
  });
  assert.ok(!stored.includes(env.SIP_FAMILY_CODE)); assert.ok(!stored.includes(env.OPENAI_API_KEY)); pass('API key and family code are absent from client storage and record backups');
  await page.locator('[data-tab=settings]').click(); await page.locator('[data-act=connect]').click(); await page.locator('[data-act=logout]').click();
  await page.waitForFunction(() => !document.querySelector('#sheet').open);
  await page.locator('[data-tab=records]').click(); assert.ok(await page.locator('.note-card').count() > 0); pass('revoking this device leaves local notes intact');
  await page.locator('[data-tab=records]').click(); await page.locator('[data-act=capture]').click(); await page.locator('[name=scanText]').fill('다시 승인해도 보존할 노트'); await page.locator('#scan-consent').check(); await page.locator('#analyze-scan').click(); await page.locator('#scan-approval').waitFor(); await page.locator('#scan-approval').click();
  await page.locator('[name=name]').fill('다시 승인한 기기'); await page.locator('[name=code]').fill(env.SIP_FAMILY_CODE); await page.locator('#family-form [type=submit]').click();
  await page.locator('#analyze-scan').waitFor(); assert.equal(await page.locator('[name=scanText]').inputValue(), '다시 승인해도 보존할 노트'); pass('approval from an interrupted scan restores the entered content');
  await page.locator('#sheet-close').click();
  for (const width of [320, 390, 768, 1024]) { await page.setViewportSize({ width, height: 844 }); await page.locator('[data-tab=settings]').click(); await page.waitForTimeout(100); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)); } pass('family settings fit 320/390/768/1024px');
  await page.locator('[data-tab=records]').click(); await page.evaluate(() => navigator.serviceWorker.ready); await context.setOffline(true); await page.reload(); await page.locator('.note-card').first().waitFor(); pass('AI outage/offline does not prevent reading existing records');
  assert.deepEqual(errors, []); pass('no uncaught browser errors');
  await writeFile(new URL('family-browser-results.json', resultDir), JSON.stringify({ passed: checks.length, checks, errors, upstream: 'mock-only', liveProviderCalls: 0 }, null, 2));
} catch (e) { await page.screenshot({ path: new URL('family-failure.png', resultDir).pathname, fullPage: true }).catch(() => {}); throw e; }
finally { release?.(); await browser.close(); await new Promise(r => server.close(r)); await rm(dir, { recursive: true, force: true, maxRetries: 3 }); }
