import http from'node:http';import{readFile}from'node:fs/promises';import{fileURLToPath}from'node:url';import path from'node:path';import os from'node:os';
import{Vault,token,digest,equal,passwordHash,passwordOK}from'./vault.mjs';import{analyze,reviews}from'./providers.mjs';import{oauthConfig,beginOAuth,finishOAuth,credentialFor}from'./oauth.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const LIFE=30*86400000;
export function makeServer(env=process.env,fetcher=fetch){const configured=Boolean(env.SIP_MASTER_KEY&&env.SIP_PUBLIC_ORIGIN);const origin=env.SIP_PUBLIC_ORIGIN||'http://localhost:8134';const u=new URL(origin);if(configured&&u.protocol!=='https:'&&!(env.SIP_ALLOW_HTTP_DEV==='1'&&['localhost','127.0.0.1'].includes(u.hostname)))throw new Error('인증 서버는 HTTPS가 필요합니다.');const secure=u.protocol==='https:',vault=configured?new Vault(path.join(env.SIP_DATA_DIR||path.join(os.homedir(),'.sip-journal'),'credentials.enc'),env.SIP_MASTER_KEY):null;const rate=new Map();
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(s=>s.trim().split('=').slice(0,2)).filter(x=>x.length===2));
function cookie(res,name,value,max=30*86400){const prev=res.getHeader('Set-Cookie')||[];res.setHeader('Set-Cookie',[...(Array.isArray(prev)?prev:[prev]),`${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${max}${secure?'; Secure':''}`]);}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function throttle(key,max=12){const now=Date.now();if(rate.size>5000)for(const[k,v]of rate)if(v.end<now)rate.delete(k);let r=rate.get(key);if(!r||r.end<now){r={count:0,end:now+60000};rate.set(key,r);}if(++r.count>max)throw new Error('요청이 많아요. 1분 뒤 다시 시도해 주세요.');}
async function getUser(req){const c=cookies(req),sessionKey=digest(c.sip_session||''),s=await vault.load(),r=s.sessions[sessionKey];if(!r||r.expires<Date.now()||!s.users[r.user])return null;return {id:r.user,key:sessionKey,user:s.users[r.user]};}
async function newSession(res,userId){const value=token();await vault.transaction(s=>{for(const[k,v]of Object.entries(s.sessions))if(v.expires<Date.now())delete s.sessions[k];s.sessions[digest(value)]={user:userId,expires:Date.now()+LIFE};});cookie(res,'sip_session',value);return value;}
async function status(req,res,user=null){let csrf=cookies(req).sip_csrf;if(!csrf||!/^[-\w]{40,60}$/.test(csrf)){csrf=token();cookie(res,'sip_csrf',csrf);}if(!configured)return {configured:false,user:null,csrf,connected:{}};user=user||await getUser(req);if(user){await vault.transaction(s=>{if(s.sessions[user.key])s.sessions[user.key].expires=Date.now()+LIFE;});cookie(res,'sip_session',cookies(req).sip_session);}return {configured:true,user:user?.user.label||null,csrf,connected:{gemini:Boolean(user?.user.keys?.gemini),openai:Boolean(user?.user.keys?.openai||user?.user.oauth?.openai?.inference)},oauth:{google:Boolean(oauthConfig('google',env)),openai:Boolean(oauthConfig('openai',env))}};}
async function readBody(req){if(Number(req.headers['content-length'])>11000000)throw new Error('요청 용량이 너무 큽니다.');let total=0;const chunks=[];for await(const chunk of req){total+=chunk.length;if(total>11000000)throw new Error('사진은 최대 3장으로 줄여 주세요.');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');}catch{throw new Error('요청 형식이 올바르지 않습니다.');}}
return http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','geolocation=(), microphone=()');const url=new URL(req.url,origin),pathname=url.pathname.replace(/^\/(?:code\/)?sip\//,'/');try{
 if(pathname.startsWith('/api/')){res.setHeader('Cache-Control','no-store');const route=pathname.slice(5),c=cookies(req);if(req.method==='GET'&&route==='session')return json(res,200,await status(req,res));if(!configured)return json(res,503,{error:'AI 인증 서버가 아직 활성화되지 않았어요.'});
 const auth=await getUser(req);const om=/^oauth\/(google|openai)\/(start|callback)$/.exec(route);if(om&&req.method==='GET'){throttle('oauth:'+req.socket.remoteAddress,20);const provider=om[1];if(om[2]==='start'){const browser=token();cookie(res,'sip_oauth',browser,600);const redirect=await beginOAuth(provider,env,vault,browser,origin,auth?.id||null,fetcher);res.writeHead(302,{Location:redirect});return res.end();}const id=await finishOAuth(provider,url,env,vault,c.sip_oauth||'',auth?.id||null,fetcher);cookie(res,'sip_oauth','',0);await newSession(res,id);res.writeHead(302,{Location:'/sip/#settings'});return res.end();}
 if(req.method!=='POST')return json(res,405,{error:'허용하지 않는 요청입니다.'});if(req.headers.origin!==origin||!equal(req.headers['x-sip-csrf']||'',c.sip_csrf||'')||!c.sip_csrf)return json(res,403,{error:'이 앱에서 다시 요청해 주세요.'});const body=await readBody(req);
 if(route==='login'){throttle('login:'+req.socket.remoteAddress,8);const username=String(body.username||''),password=String(body.password||'');if(!/^[A-Za-z0-9_-]{3,40}$/.test(username)||password.length<12||password.length>200)throw new Error('이름은 영문·숫자 3~40자, 비밀번호는 12자 이상으로 입력해 주세요.');const snapshot=await vault.load(),id='local_'+username.toLowerCase(),existing=snapshot.users[id];if(existing){if(!existing.password||!await passwordOK(password,existing.password))throw new Error('로그인 정보를 확인해 주세요.');}else{if(!env.SIP_INVITE_CODE||env.SIP_INVITE_CODE.length<24||!equal(body.invite||'',env.SIP_INVITE_CODE))throw new Error('로그인 정보 또는 가족 초대 코드를 확인해 주세요.');const hashed=await passwordHash(password);await vault.transaction(s=>{if(s.users[id])throw new Error('이미 등록된 이름입니다.');s.users[id]={label:username,password:hashed,keys:{},oauth:{}};});}const value=await newSession(res,id);req.headers.cookie=(req.headers.cookie||'')+'; sip_session='+value;return json(res,200,await status(req,res));}
 if(!auth)return json(res,401,{error:'로그인이 필요합니다. 설정에서 다시 연결해 주세요.'});
 if(route==='logout'){await vault.transaction(s=>{delete s.sessions[auth.key];});cookie(res,'sip_session','',0);return json(res,200,{ok:true});}
 if(route==='keys'){if(!['openai','gemini'].includes(body.provider)||typeof body.key!=='string'||!/^[-A-Za-z0-9_]{20,500}$/.test(body.key))throw new Error('API 키 형식을 확인해 주세요.');await vault.transaction(s=>{s.users[auth.id].keys[body.provider]=body.key;});return json(res,200,{ok:true});}
 if(route==='disconnect'){if(!['openai','gemini'].includes(body.provider))throw new Error('AI 종류를 확인해 주세요.');await vault.transaction(s=>{delete s.users[auth.id].keys[body.provider];delete s.users[auth.id].oauth[body.provider];});return json(res,200,{ok:true});}
 if(route==='analyze'||route==='reviews'){throttle('ai:'+auth.id,10);if(!['openai','gemini'].includes(body.provider))throw new Error('AI 종류를 확인해 주세요.');const credential=await credentialFor(auth.id,body.provider,env,vault,fetcher);const result=route==='analyze'?await analyze(body,credential,env,fetcher):await reviews(body,credential,env,fetcher);return json(res,200,result);}return json(res,404,{error:'지원하지 않는 요청입니다.'});}
 if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);return res.end();}if(url.pathname==='/'||url.pathname==='/sip'){res.writeHead(302,{Location:'/sip/'});return res.end();}const relative=pathname==='/'?'index.html':decodeURIComponent(pathname.slice(1));if(!/^(index\.html|manifest\.webmanifest|sw\.js|version\.json|README\.md|assets\/[\w.-]+)$/.test(relative)){res.writeHead(404);return res.end('Not found');}const file=path.join(ROOT,relative),data=await readFile(file),ext=path.extname(file),types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.md':'text/plain'};res.writeHead(200,{'Content-Type':(types[ext]||'application/octet-stream')+'; charset=utf-8','Cache-Control':relative==='sw.js'?'no-store':'no-cache'});return res.end(req.method==='HEAD'?undefined:data);
 }catch(e){if(res.headersSent)return res.end();if(pathname.startsWith('/api/'))return json(res,400,{error:e.message||'요청을 완료하지 못했어요.'});res.writeHead(e.code==='ENOENT'?404:500);res.end('요청한 파일을 열지 못했습니다.');}});}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const server=makeServer();server.listen(Number(process.env.PORT)||8134,process.env.HOST||'127.0.0.1',()=>console.log('Sip Journal server ready'));}
